### ISSUE TITLE
Getting attacked on a boat by a creeper causes a game crash.

### ISSUE THREAD

**Issue by Bu-Gee** [Wuzzy2/MineClone2-Bugs#102]
I was on a boat exploring when I got attacked by a creeper and the game crashed to the game splash screen.  When I reloaded the game, I was dead or died nearly instantly, I couldn't tell which) and the game crashed again this time requiring me to kill off minetest and restart.  A third reload did allow me to respawn and carefully get off the boat, kill the creeper, and retrieve my stuff.

I will post a link to the appropriate part of the video once I've gotten it uploaded and posted on YouTube.

But in the mean time, here is the log of the initial crash:

> 2017-02-26 11:48:59: ACTION[Server]: player singleplayer crafts
> mcl_boats:boat_jungle
> Unknown chunk found in mesh base - skipping
> Loaded mesh: mobs_sand_monster.b3d
> Unknown chunk found in mesh base - skipping
> Loaded mesh: mobs_sand_monster.b3d
> 2017-02-26 11:49:20: WARNING[Server]: Undeclared global variable "v"
> accessed at
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:54
> 2017-02-26 11:49:20: WARNING[Main]: Irrlicht: Unknown data object in
> animation of .x file: Header
> 2017-02-26 11:49:22: ACTION[Server]: singleplayer right-clicks object
> 1031: LuaEntitySAO at (14,1.5,31)
> 2017-02-26 11:50:20: ERROR[Main]: ServerError: Lua: Runtime error from
> mod 'mcl_boats' in callback luaentity_Step(): Runtime error from mod
> 'mcl_boats' in callback luaentity_Punch():
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:63:
> attempt to index a nil value
> 2017-02-26 11:50:20: ERROR[Main]: stack traceback:
> 2017-02-26 11:50:20: ERROR[Main]:
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:63: in
> function
> <....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:57>
> 2017-02-26 11:50:20: ERROR[Main]:       [C]: in function 'punch'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:583: in
> function 'entity_physics'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:1481: in
> function 'do_states'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2228: in
> function
> <...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2116>
> 2017-02-26 11:50:20: ERROR[Main]: stack traceback:
> 2017-02-26 11:50:20: ERROR[Main]:       [C]: in function 'punch'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:583: in
> function 'entity_physics'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:1481: in
> function 'do_states'
> 2017-02-26 11:50:20: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2228: in
> function
> <...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2116>
> 2017-02-26 11:50:20: ACTION[Server]: singleplayer leaves game. List of
> players:
> Cannot lock down 207603658 byte memory area (Cannot allocate memory)
> Cannot lock down 82274202 byte memory area (Cannot allocate memory)
> Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
> JackClient::AcquireSelfRealTime error
> Loaded texture: /home/bu/.minetest/games/MineClone2/menu/overlay.png
> Loaded texture: /home/bu/.minetest/games/MineClone2/menu/footer.png
> Loaded texture: /home/bu/.minetest/games/MineClone2/menu/header.png

And here is the log of the second crash, after restarting which required me to kill minetest:

> 2017-02-26 11:51:56: ACTION[Server]: singleplayer [127.0.0.1] joins
> game.
> 2017-02-26 11:51:56: ACTION[Server]: singleplayer joins game. List of
> players: singleplayer
> 2017-02-26 11:51:57: WARNING[Server]: Undeclared global variable "v"
> accessed at
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:54
> 2017-02-26 11:51:57: WARNING[Main]: Irrlicht: Unknown data object in
> animation of .x file: Header
> 2017-02-26 11:51:59: ERROR[Main]: ServerError: Lua: Runtime error from
> mod 'mcl_boats' in callback luaentity_Step(): Runtime error from mod
> 'mcl_boats' in callback luaentity_Punch():
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:69:
> attempt to index a nil value
> 2017-02-26 11:51:59: ERROR[Main]: stack traceback:
> 2017-02-26 11:51:59: ERROR[Main]:
> ....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:69: in
> function
> <....minetest/games/MineClone2/mods/ITEMS/mcl_boats/init.lua:57>
> 2017-02-26 11:51:59: ERROR[Main]:       [C]: in function 'punch'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:583: in
> function 'entity_physics'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:1481: in
> function 'do_states'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2228: in
> function
> <...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2116>
> 2017-02-26 11:51:59: ERROR[Main]: stack traceback:
> 2017-02-26 11:51:59: ERROR[Main]:       [C]: in function 'punch'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:583: in
> function 'entity_physics'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:1481: in
> function 'do_states'
> 2017-02-26 11:51:59: ERROR[Main]:
> ...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2228: in
> function
> <...bu/.minetest/games/MineClone2/mods/ENTITIES/mobs/api.lua:2116>
> 2017-02-26 11:51:59: ACTION[Server]: singleplayer leaves game. List of
> players:
> ^C2017-02-26 11:52:13: [Main]: INFO: signal_handler(): Ctrl-C pressed,
> shutting down.
> Cannot lock down 207603658 byte memory area (Cannot allocate memory)
>

**Comment by Bu-Gee** [comment]
Sorry I forgot to add that this is for version 0.12.1 + GIT pulls through "Update HUD Bars mod to version 1.7.1" (commit d3b3c596bd3f029ed690959384f474baab31a8c6)

**Comment by Bu-Gee** [comment]
Okay, the video is up. Here is a [link](https://youtu.be/M-QNeOetjqw?t=42m22s) and if it doesn't prod you to the correct part of the video, it is approximately at time 42:22.

**Comment by Wuzzy2** [comment]
(Hopefully) fixed since be145ea22e72f749f9c99c69daeefb97b3b282af.

**Comment by Bu-Gee** [comment]
I can confirm that this now appears to be fixed for me.
