### ISSUE TITLE
TNT can be defuse it like in old version Minecraft of survival test on subgame version 0.12.1

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#103]
Once TNT ignited, activated TNT entity has a health of 10 (5 hearts) and armor is fleshy 100
![screenshot_20170226_190426](https://cloud.githubusercontent.com/assets/13905392/23341768/cd3367c0-fc56-11e6-9fbc-e63d4bd887cc.png)

Can be defuse the TNT using strong sword possible to defuse. If you trying to defuse and get TNT back in survival mode, it will drop nothing.

@Wuzzy2, why you did stop doing project or doing to take a break?

**Comment by Wuzzy2** [comment]
Good find. Confirmed. :+1:

I have not stopped this project at all. I'm just not making commits in the master branch at the moment, still working on digging times.

**Comment by Wuzzy2** [comment]
Fixed in a18a9c5f70a6849afd8dd060e2dfdaac56c94679.
