### ISSUE TITLE
Zombies get stuck if ceiling is 2 blocks tall

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#104]
If there is only a 2 block gap between the floor and ceiling, zombies are not able to move forward. they can turn, but not (easily) move. 

My guess is that they try to jump or are just too tall to move around.

Tested commit  d3b3c596bd3f029ed690959384f474baab31a8c6

**Comment by Wuzzy2** [comment]
Fixed.
