### ISSUE TITLE
In-game help

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#11]
Probably just add the Help modpack with tons of texts for MineClone 2.

https://forum.minetest.net/viewtopic.php?f=9&t=15912&p=240152

**Comment by WSDguy2014** [comment]
It supposed to be tutorial mode in console versions of Minecraft, not on PC?

**Comment by Wuzzy2** [comment]
I'm not aware of a tutorial mode, but I do not intend to add a tutorial. But a simple getting-started guide might just sneak in.

**Comment by Wuzzy2** [comment]
The Help modpack has been added as of 0.4.15.
