### ISSUE TITLE
Eating while not hungry..

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#110]
Currently in MineClone2 you can eat foods while hunger bar is full, however, you should not be able to eat food until hunger bar decreases.

**Comment by WSDguy2014** [comment]
Some foods like enchanted golden apple, can still eat even it's not hungry to get positive effects.

**Comment by Wuzzy2** [comment]
I need to check this first.

**Comment by Wuzzy2** [comment]
Hunger has been reworked in 0.19.0 and this one has been fixed in the process.
