### ISSUE TITLE
Falling anvil entity changes direction + model problem in subgame version 0.13.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#111]
How to reproduce:

Place on any fence type, for example wall on bottom, any block on middle and anvil on top (make sure is facing west/east direction).
![screenshot_20170228_180602](https://cloud.githubusercontent.com/assets/13905392/23413318/f56c2606-fde0-11e6-91b5-48c8b754c8fd.png)
Break any block on middle, falling sand entity like anvil changes direction north/south direction.
![screenshot_20170228_180613](https://cloud.githubusercontent.com/assets/13905392/23413510/8ef099ba-fde1-11e6-9096-29c6ecf318ed.png)

Then it lands it and turns back to west/east direction.

@Wuzzy2, why anvil model small? Can you change a model to look same as Minecraft?
![screenshot_20170228_180651](https://cloud.githubusercontent.com/assets/13905392/23413482/72a49d10-fde1-11e6-9253-979f5f23b6d5.png)

**Comment by Wuzzy2** [comment]
I reported this bug for Minetest:
https://github.com/minetest/minetest/issues/5324

**Comment by Wuzzy2** [comment]
Fixed!
