### ISSUE TITLE
No rare pink sheep spawning?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#119]

**Comment by kwadroke** [comment]
I happened to see one the other day, but, it was before the fix for dropping the correct colored wool. Haven't seen one since. Been mostly playing an older map, so it might not take advantage of some of the code changes.

**Comment by Wuzzy2** [comment]
Confirmed. Probably I fucked up the probabilities.

**Comment by Wuzzy2** [comment]
OK, I just saw a pink sheep spawn! This issue can be closed. :P 
And I was unable to find a flaw in the probability code, so you were probably just unlucky.

Note that pink sheep are extremely rare at only 0.164%.
