### ISSUE TITLE
Consumes armor and others while player dies in subgame version 0.13.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#120]
I was playing on my singleplayer survival world, i died from fall damage while trying to touch a wall sometimes without hitting on ground (annoying bug), drops items inside of blocks (another bug) and important is armor. If it has full set of diamond armor for example, and die, it deletes it. Also i found problem, it consumes items while on 2x2 crafting grid, how to reproduce:
Jump off 80 blocks high, then quickly open inventory and move items on 2x2 crafting grid without closing inventory screen, before die, now should die on fall damage and it leaves items that contains on 2x2 crafting grid without closing inventory screen and did not dropped (Same thing on 3x3 crafting table). I didn't tested in multiplayer for example: put items on 2x2 crafting grid then turn off the server, it should be auto kicked and relog in (turn on the server first) it should be leave items that contains on 2x2 crafting grid without closing inventory screen and did not dropped.

**Comment by Wuzzy2** [comment]
Thanks for testing. Will be fixed soon.

**Comment by Wuzzy2** [comment]
> I was playing on my singleplayer survival world, i died from fall damage while trying to touch a wall sometimes without hitting on ground (annoying bug)

Please explain in detail. I don't understand.

> drops items inside of blocks (another bug)

Confirmed. I suggested Minetest change for this: https://github.com/minetest/minetest/issues/5297

Armor and crafting grid contents should now drop on death.
The crafting grdi contents are now also dropped when the player leaves or joins. Good job for thinking about multiplayer as well, I would have totally forgotten this. Silly me.

**Comment by WSDguy2014** [comment]
> Please explain in detail. I don't understand.

It's hard to tell, reproducing bug is difficult to do (i didn't tested in minetest_game subgame). I made a video that i can confirm on MineClone 2 subgame: https://www.youtube.com/watch?v=nwH-C4SvBmE
Watch video at the end.

**Comment by Wuzzy2** [comment]
Okay, this looks an engine bug. Can you also test this in Minetest Game? If it happens there, too, I close this issue and you should report it to the Minetest bug tracker instead.

**Comment by WSDguy2014** [comment]
I tested in minetest_game subgame and its confirmed too.
https://www.youtube.com/watch?v=9G1zKrO7NgA

**Comment by WSDguy2014** [comment]
@Wuzzy2 https://github.com/minetest/minetest/issues/5330
