### ISSUE TITLE
Desert temple generates lower to water ocean in subgame version 0.13.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#121]
![screenshot_20170301_222620](https://cloud.githubusercontent.com/assets/13905392/23479887/99de8cd6-fece-11e6-8441-dcc38f72e925.png)

**Comment by Wuzzy2** [comment]
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed. Desert temples now only generate in deserts. This is done by increasing the height in which the temples can generate. The bug was that desert temples only generated near sea level at beaches, which was clearly wrong.
