### ISSUE TITLE
Water buckets and lava buckets are stackable in subgame version 0.13.0?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#123]

**Comment by Wuzzy2** [comment]
I'm not sure about this one. I will only change this if I know for sure that lava and water buckets are not stackable in Minecraft 1.11, PC edition.

**Comment by WSDguy2014** [comment]
For example: if you put 5 lava buckets on fuel slot and put in wet sponge on cooking slot, consumes 1 lava bucket and won't turn into empty bucket, it remains 4 lava buckets, but, I tested to put 1 lava bucket on fuel slot and put on wet sponge on cooking slot, will turn empty bucket, but if i leave empty bucket on fuel slot (can't be put back on fuel slot), should get turned into normal sponge and it fills water in fuel slot if it detects empty bucket.

**Comment by Wuzzy2** [comment]
Right. I can confirm that only one lava bucket at a time is allowed to be in the fuel slot of furnaces. This must be fixed.
I can also confirm that empty buckets must become water buckets when draining wet sponges.
This must have totally slipped by mind. XD

However I still do not know if lava buckets *in general* are allowed to be stacked. If I remember correctly, I think “yes”, but correct me if I'm wrong.

**Comment by Wuzzy2** [comment]
As of 410d9bbaa41448c9697b12a3842d20e2d97d1284, the following changes have been applied:

* Only one lava bucket can be placed into the furnace fuel slot
* A single empty bucket can be placed into the furnace fuel slot
* Cooking a wet sponge will turn an empty bucket in the fuel slot to a water bucket

**Comment by WSDguy2014** [comment]
I tested in 0.14.0 and does not have any issues.
