### ISSUE TITLE
Dropped items follow player for a long distance (aka “homing cobble”)

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#128]
If you stand near a dropped item (so that the item flies towards you) and quickly run away, the item will follow you even over a long distance.

0.14.0

**Comment by tobyplowy** [comment]
> homing cobble

XD

**Comment by Wuzzy2** [comment]
I finally fixed this annoying bug as of f116bcfb48237265e76cbf6a919093552315f0d3, among some other item entity-related bugs.
