### ISSUE TITLE
不兼容minetest_game

### ISSUE THREAD

**Issue by zaoqi** [Wuzzy2/MineClone2-Bugs#130]
所以很多mod不能工作

**Comment by Wuzzy2** [comment]
Sorry, I only understand English or German.
Please only file issues in these languages.

I'm closing this issue because of a language barrier. :-(

**Comment by kwadroke** [comment]
Incase someone else comes across this:
According to Google Translate: "所以很多mod不能工作" = "So a lot of mod can not work"
See issue #131
