### ISSUE TITLE
Incompatible minetest_game,

### ISSUE THREAD

**Issue by zaoqi** [Wuzzy2/MineClone2-Bugs#131]
so many mod can't work.

**Comment by zaoqi** [comment]
Such as creative.is_enabled_for(name)

**Comment by Wuzzy2** [comment]
Yes, it is totally incompatible, I agree.

MineClone 2 and Minetest Game are **very** different. I do not plan any compability between the two.

But I think implementing `creative.is_enabled_for` sounds very reasonable, as well as a per-player creative mode.
I will close this issue as I generally do not aim for compability. But I open a new issue for per-player Creative Mode and `creative.is_enabled_for`.
