### ISSUE TITLE
Placing a ladder consumes 2 ladders per placing in subgame version 0.14.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#134]
When it's failed to placing here, it consumes 1 ladder:
![screenshot_20170305_135620](https://cloud.githubusercontent.com/assets/13905392/23587032/8d2369d2-01ab-11e7-9026-1f86b6649728.png)

**Comment by Bu-Gee** [comment]
Just to add to it:  It looks like if you have 1 ladder segment in the slot, you can place just the one ladder, but if you have more, it will subtract two from that slot.

**Comment by Bu-Gee** [comment]
Here is a link to it happening the video from my stream this morning:  https://youtu.be/tXWNSb4WJdo?t=27m

If it doesn't immediately queue you up, just go to 27:00.

**Comment by Wuzzy2** [comment]
LOL!
This bug is AWESOME (and I am stupid)!
It almost makes me sad to fix this bug. :D

**Comment by Wuzzy2** [comment]
Fixed in 7915ca89387ed97850ab1d52277405712aa04e17.
