### ISSUE TITLE
There is no way to make weather clear with sleeping in subgame version 0.14.0?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#135]
For example, if weather currently thunderstorm, should can sleep on day or night, to get rid of thunderstorm and make weather clear if player is wakes up.

http://minecraft.gamepedia.com/Bed

**Comment by Wuzzy2** [comment]
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed!

f3919cace9c43eaf72e0916f78021d0077f7d22d
