### ISSUE TITLE
Automating furnace using hopper does not update/start cooking.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#136]
I made a simple automated furnace like this:
![screenshot_20170305_165511](https://cloud.githubusercontent.com/assets/13905392/23588321/87eabd58-01c4-11e7-8ed4-79e25ed4288f.png)
How to reproduce: make a simple automated furnace, like i did, put cookable items on top of chest, then on items for fuel on sides chest, and does not update/start cooking, needs to be manually start.

Tested in subgame version 0.14.0

**Comment by Wuzzy2** [comment]
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed in 7ecae53502c5f5051e0392bb6e57bdb5b164546d.
