### ISSUE TITLE
Snow layers affected by gravity in "minetest_game" subgame? 

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#138]
I saw a snow layer block, that has a feature affects by gravity first time, that i played on minetest_game subgame in Minetest version 0.4.13 (i'm not sure). But, i watched a video "✔ Minecraft: 10 Things You Didn't Know About Snow" by 'iDeactivateMC', it has an exclusive feature in Minecraft: Pocket Edition, which snow layer falls like a falling block entity, but it has 3D block looking, like a Anvil [(click here](https://www.youtube.com/watch?v=lTbLCUKb4uA&t=2m49s)), but in Minetest at minetest_game look different, falling block entity now looks like an snowball item icon for inventory/selecting an item on hotbar instead of 3D block looking.
Developers Mojang stole an idea in Minetest feature for adding snow layers affected by gravity and added a falling block entity 3D model for snow layer in Minecraft: Pocket Edition version Alpha 0.12.1 build 1??? I don't know if its added snowball (placing blocks only and affects by gravity) in Minetest version 0.4.7 on minetest_game subgame before Minecraft: Pocket Edition version Alpha 0.12.1 build 1?

**Comment by Wuzzy2** [comment]
Is this a bug report? If yes, what's the bug?
If not, I don't care about Internet drama about who allegedly “stole” ideas from whom.

**Comment by WSDguy2014** [comment]
> Is this a bug report? If yes, what's the bug?

It's the information for optional dependencies mod for MineClone 2 subgame to get enable more features. I don't know for sure.

**Comment by Wuzzy2** [comment]
I still don't get it. You can already add mods to MineClone 2, just create mods which are compatible with it.
If this was the “bug report”, I'm going to close it as invalid.

**Comment by WSDguy2014** [comment]
Yeah, mods for MineClone 2 to enable more exclusive Minecraft features.
