### ISSUE TITLE
Pistons can be pushed/pull any door

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#140]
Tested wooden oak door in subgame version 0.14.0
It used for breaking unbreakable blocks, like bedrock.

**Comment by Wuzzy2** [comment]
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed in 302f66977a44ea8eccef7a4522ea04b7e4d28544.

When a piston pushes a door now, the door drops as an item.
