### ISSUE TITLE
Furnaces continue to smelt when output is full / faster smelting cheat

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#141]
Furnaces continune to smelt the items when the output is full. Some items get destroyed in the process.

**Comment by Bu-Gee** [comment]
I can't tell if this is the same bug, but it sounds similar.  Please let me know if you want me to open this as a separate issue:

I had some iron ore smelting and a unit was nearly complete when I swapped it out for a raw porkchop.  The output slot had iron in it, but the instant I removed it from the output, I got a cooked pork chop WAY sooner than I should have.  It is tough to explain.

The video will hopefully make it clearer:  https://youtu.be/oWHXJshiiPw?t=51s

**Comment by Wuzzy2** [comment]
Confirmed. It's OK.

**Comment by Wuzzy2** [comment]
Cooking progress is now reset to start whenever the furnace detects a new item in the input slot. The “cheat” in the video no longer works. :-)

The first issue still remains.

**Comment by Wuzzy2** [comment]
Fixed.
The furnace behaviour is now this:
If the output is full and the smelting progress reaches 100%, the item is not cooked and the smelting progress is simply reset. This should be simple enough and forces player to keep the furnace output clean.

Previously, if the cooking continued while the output was full, the internal cooking progress counter was still increasing so if you left the furnace for a long time, then cleared the output, the furnace would instantly cook a lot of items.
