### ISSUE TITLE
Unable to use pick on stairs or furnaces and use axe on chests

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#142]
When trying to use picks (stone or iron) on to break stairs or furnaces nothing happens. When trying to use axes to break chests, nothing happens.

Last tested on 34a531062b54e3de7a8884b202d267b69206caec

**Comment by kwadroke** [comment]
Swords, shovels, axes, nor picks will break stairs, furnaces or chests.

**Comment by Wuzzy2** [comment]
Confirmed. :-(((

**Comment by Wuzzy2** [comment]
OK, this should be fixed now.

**Comment by kwadroke** [comment]
Works fine now. Thanks.
