### ISSUE TITLE
Furnaces Don't Appear To Work At All

### ISSUE THREAD

**Issue by Bu-Gee** [Wuzzy2/MineClone2-Bugs#144]
I was continuing my "let's play" series this morning and I was experimenting with hoppers just to see what they would do and nothing worked.  The furnaces completely refused to smelt anything even when I put things into them normally.

Here's the part of the video with the hoppers:  https://youtu.be/M1xO_sR_9Is?t=33m50s
Here's the part of the video where the standalone furnace doesn't work: https://youtu.be/M1xO_sR_9Is?t=40m3s

I also tried it off-video in another save file in case the hoppers messed up this save somehow, but those furnaces do not work anymore either.

This is on a git pull through 2c16c4db690b9a85c94978d5c528536b95243630

I am wondering if the fix in #141 has anything to do with this.  While similar to #136, I don't think it is the same problem because the furnaces don't work at all.

**Comment by kwadroke** [comment]
I've seen if you remove the coal, wood or other burnable items from a non working furnace, put them in your inventory, then put them back it will start up again. That is until there is nothing that you can cook left in the furnace. Then you have to do it again most times.

**Comment by Wuzzy2** [comment]
Wow, just wow. How stupid! xD
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed in cb42fbf9bcdec6fe15b56357b986c76cc85ba568.

Thanks for the analysis.
