### ISSUE TITLE
Stone(s) drop items without a tool

### ISSUE THREAD

**Issue by DemoseDT** [Wuzzy2/MineClone2-Bugs#146]
I discovered this curious bug when I was burrowing into a mountain for security earlier today in release 0.15.0.

![stones_drop_items_without_tools](https://cloud.githubusercontent.com/assets/26317421/23781535/a48601b4-0513-11e7-9e2f-ffdcd14bf459.png)

**Comment by Wuzzy2** [comment]
Confirmed. Almost all blocks drop their drop regardless of tool. This is still on the TODO list.

**Comment by Wuzzy2** [comment]
**Finally** fixed!
