### ISSUE TITLE
You can place a torch on a ladder and have it float in mid-air.

### ISSUE THREAD

**Issue by Bu-Gee** [Wuzzy2/MineClone2-Bugs#147]
I don't know if this is a valid bug, but it sure looks weird.

I accidentally placed a torch on a ladder and it successfully placed onto the next block over, floating in mid-air.  I can never really tell if things floating in mid-air are really a problem, but I thought this one was just too out there.

Here is a link to my video where that happened: https://youtu.be/2Pj65VXTaGw?t=39m39s

**Comment by Bu-Gee** [comment]
Sorry.  This is for 0.15.0 through git commit 3bf5dfa0f842ad33b8f1c05244e0f39ea31d55e2

**Comment by Wuzzy2** [comment]
This is a valid bug. Torch placement rules in Minecraft are a bit complex, but placement on ladders is definitely forbidden.

I have just now worked on the torch code a bit to make the placement rules more Minecraft-like.
Torches can now no longer be placed at ladders. This bug is fixed.
