### ISSUE TITLE
Torches cannot be break with water, if its not flowing

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#149]
Tested in subgame version 0.15.0
![screenshot_20170310_230953](https://cloud.githubusercontent.com/assets/13905392/23813371/416fcbee-05e7-11e7-80b3-ef9377520623.png)

**Comment by Wuzzy2** [comment]
Confirmed.

**Comment by Wuzzy2** [comment]
Fixed in bb965b6d63eaad15ba94bc3c66386f7c62267e69.
