### ISSUE TITLE
Bad weather balancing

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#150]
One player claimed the weather changes too often. I should look into this.

**Comment by Bu-Gee** [comment]
I would say the weather changes very little.  I think I had snow for 6 in-game days straight followed by less than a day of sun followed by several in-game days of rain.

Without looking at the code in the slightest, it seems the weather changes very slowly when it is inclement, but nice days don't last very long.

**Comment by Wuzzy2** [comment]
Alternative weather mods:

https://forum.minetest.net/viewtopic.php?f=11&t=6854
https://forum.minetest.net/viewtopic.php?f=11&t=13886

**Comment by Wuzzy2** [comment]
Weather length should now be more or less like in MC.
