### ISSUE TITLE
Hoppers unable to collect items though the solid non-full block

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#153]
Tested in subgame version 0.15.0
![screenshot_20170315_171919](https://cloud.githubusercontent.com/assets/13905392/23955816/b76636fc-09a3-11e7-9b3d-bb77279b33c5.png)

**Comment by Wuzzy2** [comment]
I checked Minecraft Wiki, this issue is valid.

**Comment by Wuzzy2** [comment]
Fixed in 52b9d3b4527767dd70bbd57e0c9864b07a44cd36.
