### ISSUE TITLE
Breaking at activated sticky piston will drop normal piston.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#155]
How to reproduce it, in survival mode activate a sticky piston, break at activated sticky piston
![screenshot_20170315_195331](https://cloud.githubusercontent.com/assets/13905392/23963312/7d54be0a-09b9-11e7-8aed-b4b244b2e69b.png)
and it will drop normal piston as converts back to normal.
![screenshot_20170315_195338](https://cloud.githubusercontent.com/assets/13905392/23963348/a170e0f2-09b9-11e7-9ac1-bc92a5435c14.png)
Tested in subgame version 0.15.0

**Comment by Wuzzy2** [comment]
Confirmed. And fixed in 6892e45e1faec3242a90d3321f5eee3a5614670f.
