### ISSUE TITLE
LUA OOM

### ISSUE THREAD

**Issue by nictaylr** [Wuzzy2/MineClone2-Bugs#175]
ServerError: Lua: OOM error from mod 'mcl_mapgen_core' in callback environment_OnGenerated(): not enough memory

**Comment by nictaylr** [comment]
latest minetest, win64

**Comment by Wuzzy2** [comment]
I need more information than just that. When exactly did this occour? What did you do before the crash?
Do you have exact error messages?
Can you also post the last lines of of `debug.txt` just before it crashed?
Any other infos of interest?

**Comment by nictaylr** [comment]
when occur? few second after starting game
what before? nothing, just wait few second after world load
i post exact error before
i will look for more info of interest

**Comment by Wuzzy2** [comment]
OK, I guess my mapgen code is just crap. :D 

Paramat posted some Lua optimizations. I might need them to fix this bug.
https://forum.minetest.net/viewtopic.php?f=18&t=16043

**Comment by Wuzzy2** [comment]
Okay, paramat's suggested memory optimizations have been applied.

bcc185f83fc007bcf85c884a90c0eac09c30109c

Please test if this OOM crash still occours.

**Comment by Wuzzy2** [comment]
I close this issue as obscure and old and it is probably fixed. Feel free to open a new issue if OOM bugs occour again.
