### ISSUE TITLE
Edit a sign only first time

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#176]
Previously, you place a sign, it does not let edit a sign first, needs to right-click on sign to edit text on sign. That's not right, must be to place a sign and needs to be edit text on sign, only can edit first time (placing a sign - let edit a text first, before complete), you cannot right-click on sign to edit text again. Only is for used as functional for map makers or something like that.

**Comment by Wuzzy2** [comment]
True story.

**Comment by Wuzzy2** [comment]
Fixed.
