### ISSUE TITLE
Falling through floor using ender pearl in subgame version 0.16.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#178]
I was recorded on my world tour video, i have to finish recording by falling through floor using ender pearl and i did it first time: https://www.youtube.com/watch?v=RHc_KB8caCY&t=9m38s

I didn't test it in subgame version 0.17.0

**Comment by Wuzzy2** [comment]
Fixed in 447489f7a99cd92ac1f2515603490d598a0c65a6.
