### ISSUE TITLE
Flint/Steel on Netherrack

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#180]
Using Flint/Steel on Netherrack should burn forever or until put out by player or water. This is some times used inside player homes for a fireplace decoration. Players just have to be smart enough to surround the flame with non-burnable blocks and possibly a few iron bars in front of flame to act as a grate. Currently, if you use Flint/Steel on Netherrack in MineClone2, it will burn for several seconds then extinguish.

**Comment by Wuzzy2** [comment]
Yes.
What happens in MC when you remove the netherrack below this eternal fire?

**Comment by Wuzzy2** [comment]
OK, fixed. Flint and steel creates eternal fire on netherrack.

I close this issue, but I still want to know the answer to the question above.

**Comment by tobyplowy** [comment]
@Wuzzy2 The fire gets instantly removed if you brake the netherrack

**Comment by Wuzzy2** [comment]
Good. I chose the same behaviour for MCL2. :-)
