### ISSUE TITLE
Colord beds and new model

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#182]
@Wuzzy2 So in the unstable version of Minecraft (17w15a i think) they added colord beds and the beds also have a new model
[You can get the new model here](https://github.com/22i/minecraft-voxel-blender-models/tree/master/0%20object%20models/bed) credits​ to 22i 

More stuff about 17w15a can be found [here](https://minecraft.net/en-us/article/minecraft-snapshot-17w15a)

**Comment by Wuzzy2** [comment]
Beds are now 3D. Colors are still TODO.

**Comment by Wuzzy2** [comment]
:bed: :balloon: :tada: :balloon: :bed: :tada: :balloon: :tada: :balloon:  :bed:
Colored beds have been added!

MineClone 2 has now beds like in MC 1.12.
