### ISSUE TITLE
Jump out of the water fails

### ISSUE THREAD

**Issue by UgnilJoZ** [Wuzzy2/MineClone2-Bugs#184]
I can not jump out of the water.
For example this fails:
![I can not jump out of this](https://i.imgsafe.org/f5c02467c5.png)
My only possibility is to remove one dirtblock and quickly jump before the water flows in.
(Or use slabs on the beach xD)

I have compiled Minetest today and pulled this repository a few minutes ago.
Other subgames are working flawlessly, so I suspect the bug is here.

**Comment by Wuzzy2** [comment]
I do not support experimental Minetest versions and don't want to.

Try Minetest 0.4.15.

**Comment by UgnilJoZ** [comment]
Sorry I bothered you with this, https://github.com/minetest/minetest/issues/5718 was biting me. No MineClone2 bug here.
