### ISSUE TITLE
Player is too high

### ISSUE THREAD

**Issue by UgnilJoZ** [Wuzzy2/MineClone2-Bugs#185]
The height of the player seems to have slighty changed or the hitbox moved, so that I cannot use doors anymore.

![Doors](https://i.imgsafe.org/f5bf8e58aa.png)
I had to dig into the floor to get into a house :)
![Single Block](https://i.imgsafe.org/f5c047017c.png)
Also walking under this dirtblock does not work, so it has nothing to do with the door itself.

**Comment by Wuzzy2** [comment]
Did you use Minetest 0.4.15?
If not, I don't guarantee anything. :P 

I also heard that the bleeding edge Minetest was very buggy recently. So I suspect this bug is a Minetest bug (in bleeding edge), and not a MineClone 2 bug.

**Comment by UgnilJoZ** [comment]
I think you are totally right. I wasn't able to figure out a "good" (=this does not happen) Mineclone commit - but a commit in Minetest itself. I am now at bisecting MT master.

Sorry for taking this to you. Great subgame, by the way!
