### ISSUE TITLE
Villagers spawning around houses with fences/gates

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#188]
I recently built a fence around my house and added a gate to give access to a farm area. Now, villagers spawn 2 to 3 at a time around my house inside the fence area. Not sure why this is happening, but it didn't start until I added the fences and gate. Usually villagers spawn around villages, not player houses. It's not super annoying, but thought I'd mention it.

**Comment by Wuzzy2** [comment]
Currently, mob spawning is not very intelligent.

Villagers spawn on gravel. Well, I could disable villager spawning for now, at the moment they are useless anyway.

**Comment by Wuzzy2** [comment]
Fixed (for now). Villagers don't spawn anymore, because there are no villages yet.
