### ISSUE TITLE
Game freezes when pathfinder errors occour

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#189]
When trying to move items in or out of inventory, items will not move without exiting to Menu and re-entering the game sometimes after the following error:

`ERROR[Server]: Pathfinder: fail to update cost map`

I've also noticed that sometimes mobs will fly into the air when this error comes up. Usually when on an raised platform or building above water.

Screenshot of error and mobs in the air:
![screenshot_20170521_142729](https://cloud.githubusercontent.com/assets/3247032/26286762/7682fd78-3e32-11e7-8ceb-291d66c9d5d6.png)

**Comment by Wuzzy2** [comment]
Woah, this looks extreme. I never saw mobs being randomly catapulted into the air so far.

I am waiting for the next Minetest release, it might fix some of the pathfinder bugs.

**Comment by leorockway** [comment]
In my case, besides not being able to interact with inventory, chests, etc. I also can't open / close doors.

**Comment by Wuzzy2** [comment]
Please re-test this in 0.23.0

**Comment by leorockway** [comment]
I will!

**Comment by leorockway** [comment]
I haven't had a single Pathfinder warning message and the game ran smoothly the whole time (I played for 1.5 hours and this issue usually happens after maybe 5 minutes of playing).

Good job!
