### ISSUE TITLE
Bone Meal usage does not remove from inventory

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#192]
When using bone meal on potatoes, wheat seed, or carrots it will not reduce the amount that you have in your inventory. You have unlimited use of the bone meal no matter how much you have.

**Comment by Wuzzy2** [comment]
Fixed in 9f5a310aae17de9f0371950a2755bc5afcdcdc11.

**Comment by kingoscargames** [comment]
now i cant get like 5 stacks of wheat in half a hour :(. XD
