### ISSUE TITLE
Items fall through floor

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#195]
Some items now fall through floor when broken. About a 50% chance of not being able to collect the items.

Minetest 0.4.15 & commit cf9f4ba976c3cef4c269014defb8470c45ab0a2e

**Comment by Wuzzy2** [comment]
@%!$&!

**Comment by Wuzzy2** [comment]
OK, after a billion commits or so, I think I now have the bug fixed.
