### ISSUE TITLE
Wrong hand place and model (200th issue)

### ISSUE THREAD

**Issue by Doloment** [Wuzzy2/MineClone2-Bugs#200]
Now:
![screenshot_20170530_111532](https://cloud.githubusercontent.com/assets/22934348/26568219/cddfb44e-452b-11e7-9db3-2308a654b6ce.png)

Must be:
![635733362039447280](https://cloud.githubusercontent.com/assets/22934348/26568234/ec1b0184-452b-11e7-8f76-871497aafd33.png)

**Comment by WSDguy2014** [comment]
@Doloment, He made a [3D hand mod](https://github.com/jordan4ibanez/newhand) , but it requires 0.4.15-dev or wait for 0.4.16

**Comment by Wuzzy2** [comment]
I don't really see the need for the 3D hand mod, changing the texture and wield scale will probably suffice. I hope.

**Comment by Wuzzy2** [comment]
I pushed a new commit with different hand texture and scale.
![New wieldhand](https://i.imgur.com/vw6rePf.png)

Is this better now? If now, please tell me exactly what you want.

**Comment by Doloment** [comment]
Yes, is better
