### ISSUE TITLE
Item entities sometimes fly away after creation

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#204]
Sometimes, after an item entity was created, it randomly (?) flies away for a moment and is not collected even if it is very close to the player.

**Must** be fixed.

**Comment by octacian** [comment]
You might find this useful (item entity from my current subgame):
https://github.com/RevDevGames/eden/blob/master/mods/eden/item_entity.lua

It's fairly advanced based off of jordan4ibanez's rewritten item_drop and tenplus1's builtin_item mod. It includes custom velocity on drop, simplified drop-lift, movement with water, magnet, improved burning. From my testing, it doesn't have any of the issues that I've experienced with the item drop here in MineClone.

**Comment by Wuzzy2** [comment]
You said “issues”. This is a plural. What are the other ones?

If I just take your mod verbatim I will lose all of the other features I already have added over the time. I would prefer to fix the existing code.
But yeah. If I don't manage to get rid of the horrible mess I have caused I guess I have to nuke it … again!

Requirements list for item entity:

* Destroyed in lava, instantly
* Falls down
* Item magnet, but not forever
* Gets pushed out of solid nodes
* Gets pushed by water flow
* No collecting by punching
* Not pointable
* Take damage like players, but have only 1 HP
* Despawn after 5 minutes
* A million other things

**Comment by Wuzzy2** [comment]
Okay, after reworking my item code, the item flying is now much rarer and it now a less serious bug, but it still sometimes happens shortly after killing a mob.

Thanks for the link, octarian. I have looked at the code.

**Comment by Wuzzy2** [comment]
After hours of debugging and refactoring, I have finally found the cause for the “random” item flying and finally fixed this horrible bug.
