### ISSUE TITLE
HUD cosmetic improvement

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#216]
In order to be more MC-like, the air-bar should be on the right, on top of the food bar. Also, the food bar should start to deplete from the left, not from the right (ie: the first drumstick to get empty is the one on the left).

**Comment by Wuzzy2** [comment]
Oops, for some reason I introduced a regression previously which indeed cause the bubbles to be at the completely wrong position. Fixed by now.

The direction (left/right) issue is a duplicate.
https://github.com/Wuzzy2/MineClone2-Bugs/issues/29
