### ISSUE TITLE
Flowers can place on any block.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#218]
For example stone.
![screenshot_20170606_222433](https://user-images.githubusercontent.com/13905392/26847821-0bb460f4-4b07-11e7-8502-ff33560ccba8.png)
Tested in subgame version 0.21.0

**Comment by Wuzzy2** [comment]
So what's the bug?
If stone is illegal, which blocks are legal? Minecraft Wiki is unclear here.

**Comment by leorockway** [comment]
Apparently they can't be planted on stone. This is what I found: "To survive, flowers must be planted on a grass or dirt block that either does not have a block any altitude above it to obstruct sun/moonlight, or is lit with at least a light level of 8. If neither of these conditions exist, the flower will quickly pop out. This attribute allows flowers to be used in the creation of light-sensitive mechanisms."

**Comment by Wuzzy2** [comment]
Fixed in c71cd66e505074d1b28cd84f9f9f352c7a23762a.
