### ISSUE TITLE
Mob explosion does not work near unbreakable blocks

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#222]
Tested in the flat mapgen, MCL2, v0.210.

If a creeper explodes near bedrock, the breakable blocks are not entirely destroyed.

**Comment by kingoscargames** [comment]
i found that already before i had a account (signed up today)

**Comment by Wuzzy2** [comment]
On a sidenote, I appreciate your reviewing and testing of MineClone 2. :+1:

**Comment by Wuzzy2** [comment]
Fixed.
