### ISSUE TITLE
Problems with skeletons in subgame version 0.21.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#223]
I was making a simple skeleton mob farm, skeletons shot arrows very very slowly. Skeletons does not have holding on bow.

https://www.youtube.com/watch?v=CDbVfEHf2yI&t=50s

Should be add skeletons holding a bow + a rare chance to spawn skeleton holding a bow on another arm.

**Comment by Wuzzy2** [comment]
Yes. I will probably tackle all those mob bugs when I start to seriously implement mobs. I think maikerumine's `mobs_mc` will help me here.
I might consider trashing some of the worst mobs first.
Currently, many mobs are in a terrible, terrible shape, I admit it! :D

**Comment by Wuzzy2** [comment]
Skeletons are now able to shoot arrows properly.
