### ISSUE TITLE
legs move weird while standing still

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#224]
if you look at the legs like for a couple of seconds they will move even when the player is standing still.
i believe that was a bug with the old player model in default and the one from 3d_armor.
look at around 0:08 of this video: https://www.youtube.com/watch?v=kSelilSKqNk (the same problem but with default).

**Comment by kingoscargames** [comment]
i discovered that the legs part of the armor layer in the new 3d_armor is mirrored the wrong way so updating wouldn't be possible without breaking textures

**Comment by kingoscargames** [comment]
and  the bottom texture for the cape is stretched

**Comment by kingoscargames** [comment]
its fixed

**Comment by Wuzzy2** [comment]
Oh, indeed. I totally forgot that. :D
