### ISSUE TITLE
unable to wear mob heads

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#225]
players should be able to wear mob heads
i am working on this: 
![screenshot_20170610_143259](https://user-images.githubusercontent.com/29333817/27002872-57bf020a-4dec-11e7-9445-a946ca524fba.png)

its actually pretty easy but it isnt using the mob textures :(, only helmet textures i created

and yes the error message is from a mod i use for survival that ads a unbreakable set of leather armor
XD

registering new armor is really easy

**Comment by kingoscargames** [comment]
and yes the error message is from a mod i use for survival that ads a unbreakable set of leather armor

**Comment by kingoscargames** [comment]
the textures and code:
![mcl_heads_creeper](https://user-images.githubusercontent.com/29333817/27003029-8ee100a0-4def-11e7-9dc3-4fdfaa2b0cbe.png)
![mcl_heads_creeper_preview](https://user-images.githubusercontent.com/29333817/27003028-8edb89e0-4def-11e7-99c8-b1715de7f376.png)
![mcl_heads_skeleton](https://user-images.githubusercontent.com/29333817/27003031-8ee4ef6c-4def-11e7-90a5-10167eee1e9e.png)
![mcl_heads_skeleton_preview](https://user-images.githubusercontent.com/29333817/27003033-8ee6b9a0-4def-11e7-9a47-318b3fdca26a.png)
![mcl_heads_steve](https://user-images.githubusercontent.com/29333817/27003032-8ee63606-4def-11e7-88b1-44f11f107070.png)
![mcl_heads_steve_preview](https://user-images.githubusercontent.com/29333817/27003030-8ee220ac-4def-11e7-8a38-81394f3988e5.png)
![mcl_heads_wither_skeleton](https://user-images.githubusercontent.com/29333817/27003034-8eef3e04-4def-11e7-9356-473c978ede50.png)
![mcl_heads_zombie](https://user-images.githubusercontent.com/29333817/27003035-8ef63b6e-4def-11e7-855a-97215f9c5522.png)
![mcl_heads_zombie_preview](https://user-images.githubusercontent.com/29333817/27003036-8efe6550-4def-11e7-88d5-51f9a9eb428a.png)

**Comment by kingoscargames** [comment]
the only bug i found with it is that it doesn't leave the armor bar empty

**Comment by kingoscargames** [comment]
are my textures and code edit actually usefull?

**Comment by Wuzzy2** [comment]
Hmmm, aren't group ratings supposed to be integers only?
I will comment your textures when I try to implement armor properly. Currently, armor is not high on my priority list.
Note I want to replace textures with 16×16 in the long run, so don't bother with 32×32 textures.

See #76.

**Comment by kingoscargames** [comment]
maybe this texturepack could be usefull?: https://www.planetminecraft.com/texture_pack/sensecraft---a-simple-pleasant-texture-pack-which-improves-upon-the-default-experience/

**Comment by Wuzzy2** [comment]
Sadly, SenseCraft does not include any licensing information which implies full copyright. So will refrain to take this texture pack.
But I will gladly take any suggestions for free/libre texture packs in issue #76.

**Comment by kingoscargames** [comment]
forgot the wither skull preview:
![mcl_heads_wither_skeleton_preview](https://user-images.githubusercontent.com/29333817/27003494-ed2c1520-4df7-11e7-82c6-06e20db31648.png)

**Comment by kingoscargames** [comment]
the skulls are shown in the combat tab in creative  when using this

**Comment by Wuzzy2** [comment]
Don't worry, I can fix this.

**Comment by Wuzzy2** [comment]
Thank you for the textures. I have added this feature now.

It is not fully complete yet, I still must fix a bug: The game behave incorrectly if you place a *stack* of heads (or pumpkins) into the armor slot.
Help text must also be update. Will work on that later today (I hope).

**Comment by kingoscargames** [comment]
the only bug i found with it is that when you have 63 human heads and pick one up from the armorstand it doesnt stack with the 63 you must drop it and pick up to stack them

**Comment by Wuzzy2** [comment]
- As I already said, mob heads can be worn now
- And placed on armor stands
- The game prevents you from having more than 1 head block/pumpkin in the head armor slot
- Armor stand allows you to take head/pumpkin if you hold a stack of the same type (unless your wielded stack is full)
- Heads and pumpkin have been removed from combat tab in Creative Mode

Everything is done! Closing.
62f755f52aa955c8ee42c728d86bf61898690b36
