### ISSUE TITLE
blazes don't use the 32x32 faithful texture

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#227]
it should use this: 
![blaze](https://user-images.githubusercontent.com/29333817/27002927-3e7918c0-4ded-11e7-9fa1-2674e0baffea.png)

**Comment by kingoscargames** [comment]
why isnt this changed already?

**Comment by Wuzzy2** [comment]
Because I have other priorities at the moment. Please be patient. I am already working like crazy on MCL2. Just look at the sheer number of issues, the number of blocks still left unimplemented, the number of mobs, the other big missing features (status effects, enchanting, etc.).

**Comment by kingoscargames** [comment]
I will close this because of https://github.com/Wuzzy2/MineClone2-Bugs/issues/76
