### ISSUE TITLE
the wither skeleton texture is weird

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#228]
i edited the faithfull one to fit the player model:
![mobs_skeleton2](https://user-images.githubusercontent.com/29333817/27002945-8a0e5a70-4ded-11e7-9292-228c85959906.png)

**Comment by kingoscargames** [comment]
if you don't want to use this one then pls use the actual 32
![wither_skeleton](https://user-images.githubusercontent.com/29333817/27002979-805a89da-4dee-11e7-8e7e-bef647fab163.png)
x texture:

**Comment by kingoscargames** [comment]
Could it be possible to use a 3 block high skeleton model with the same wield box thingy?

**Comment by Wuzzy2** [comment]
Fixed in ea841eecfbaeef90d50e848a03fceb4eee5a1d9b.

Thanks for you help. But please don't bother with mob textures in the near future, it is likely I'll throw much of the existing code away.

**Comment by kingoscargames** [comment]
so you did use my texture?
