### ISSUE TITLE
the hotbar doesnt use the 32x textures

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#229]
the right textures:
![crafting_hotbar](https://user-images.githubusercontent.com/29333817/27002954-d9308be6-4ded-11e7-8607-bcc7d50371f1.png)
![crafting_hotbar_selected](https://user-images.githubusercontent.com/29333817/27002955-d9314874-4ded-11e7-9e26-ee2bcff64e9c.png)

**Comment by kingoscargames** [comment]
is

**Comment by kingoscargames** [comment]
is it really that critical XD

**Comment by Wuzzy2** [comment]
Fixed in c843e8ca87d6e83651cdda8ef08ac665b78e0269.

**Comment by kingoscargames** [comment]
ok
