### ISSUE TITLE
Creative Mode and item dropping

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#23]
ALL dropped items should behave different and MC-like. Currently (0.10.0), it's mostly random and a lot of stuff drops but shouldn't.

**Comment by C1ffisme** [comment]
In creative mode, dug blocks should dissapear, not be dropped for the player to pick up. If a player needs a block in creative mode, they can use the pick-block button. (Usually the middle-mouse button.)

There are a few exceptions:

- Mob drops
- Items in chests, but not chests themselves.
- Blocks that are actually entities (Paintings or Item Frames)

**Comment by Wuzzy2** [comment]
Fixed in 5834224af50fdf5fb82dce5edd19cd8ed35e3c49.
