### ISSUE TITLE
(not important) bottom part of cape is stretched

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#232]
this is not important because the default character.png doesnt have a cape
<img width="203" alt="cape is weird" src="https://user-images.githubusercontent.com/29333817/27003235-340a9174-4df3-11e7-8013-3ea360f29291.png">

**Comment by Wuzzy2** [comment]
Probably all those character model issues can be fixed at once when I just grab the player model code from latest Minetest Game.

**Comment by kingoscargames** [comment]
but this model is from the old 3d_armor mod version

**Comment by kingoscargames** [comment]
should i close this?

**Comment by Wuzzy2** [comment]
No, because player model needs updating anyway.

**Comment by kingoscargames** [comment]
fixed
