### ISSUE TITLE
held blocks aren't shown in 3rd person

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#233]
maybe add the wield3d mod?

**Comment by Wuzzy2** [comment]
Good suggestion. I gladly take any suggestions to add mods which add good features.
I'll definitely look at this mod later.

**Comment by kingoscargames** [comment]
i believe it depend on default but that could be fixed

**Comment by Wuzzy2** [comment]
This is invalid, wielditems are already visible using the `wieldview` mod. It's just not very fast or well implemented and might be replaced later.

See also: https://github.com/Wuzzy2/MineClone2-Bugs/issues/250
