### ISSUE TITLE
hardened clay renamed to terracota in 1.12   :(

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#234]
i dont like this change but if you try to clone the blocks you can also just clone this :(

**Comment by Wuzzy2** [comment]
Already fixed. :P

**Comment by kingoscargames** [comment]
oh sorry i am still using the latest release cause compatabilty with 0.4.15 could break

**Comment by Wuzzy2** [comment]
Yes, compability already has broken in the very first commit after 0.4.16 because of new shiny 0.4.16 features. :D

**Comment by kingoscargames** [comment]
:(
