### ISSUE TITLE
carts dont look like the ones in mc

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#236]
some mc like textures i created for my mc texturepack:
![cart_front](https://user-images.githubusercontent.com/29333817/27003423-b0770faa-4df6-11e7-8965-893df6876299.png)
![carts_cart](https://user-images.githubusercontent.com/29333817/27003421-b074cfc4-4df6-11e7-9dad-97bafa1fd936.png)
![carts_cart_front](https://user-images.githubusercontent.com/29333817/27003420-b0741a02-4df6-11e7-8278-b9b34e2241f6.png)
![carts_cart_side](https://user-images.githubusercontent.com/29333817/27003419-b072e4ac-4df6-11e7-9dfc-a4d9f6be615c.png)
![carts_cart_top](https://user-images.githubusercontent.com/29333817/27003422-b0750462-4df6-11e7-926d-1cf5bfb8ebb4.png)

**Comment by Wuzzy2** [comment]
I appreciate your texture contributions, but I would prefer to use a complete and readily-available texture pack, simply for artistic consistency.

The MC carts are actually not 1×1×1 sized, they are a bit smaller, I think. I'm not sure if these textures would work for the minecart (haven't checked).

**Comment by kingoscargames** [comment]
the textures work for the mt model
i edited the mc texture to fit 16x16 sides but i will change to 32x later

**Comment by kingoscargames** [comment]
wait they dont work?
oh yeah i gotta rename them XD

**Comment by kingoscargames** [comment]
the cart should be renamed to cart.png

**Comment by Wuzzy2** [comment]
Note the cart model need to be changed anyway. I suggest that you make any texture contributions as if you would make them for MC, unless I say something otherwise.

I advise to stay away from mob textures for now, mobs are a horrible broken mess at the moment.

**Comment by Wuzzy2** [comment]
This doesn't look right:
![](https://i.imgur.com/Wmm8vI5.png)

**Comment by kingoscargames** [comment]
i could edit the texture it was made for the cart in mtg

**Comment by Wuzzy2** [comment]
If it looks okay, I probably include it (bear in mind the license of MineClone 2). How do you wish to be credited?


Just keep in mind the texture will probably need updating when I change the model.

**Comment by kingoscargames** [comment]
well making the cart look right is hard because it would have wheels on all sides

**Comment by kingoscargames** [comment]
could you use the model from mtg?

**Comment by Wuzzy2** [comment]
It looks meh.

**Comment by kingoscargames** [comment]
no it isnt it has different textures for the front

**Comment by kingoscargames** [comment]
this one hasnt so it has 4 wheeels

**Comment by kingoscargames** [comment]
an what does "IIRC" mean?

**Comment by kingoscargames** [comment]
![screenshot_20170610_181855](https://user-images.githubusercontent.com/29333817/27004423-4c87d822-4e09-11e7-88d4-57992cafb84b.png)
this is how my texture looks in mtg

**Comment by kingoscargames** [comment]
also when riding a minecart the character's feet are inside the model but in mtg:
![screenshot_20170610_182000](https://user-images.githubusercontent.com/29333817/27004441-859c5cfa-4e09-11e7-8c10-cf00f5399b27.png)
they are on the bottom not inside it

**Comment by kingoscargames** [comment]
does this look better:
<img width="32" alt="cart" src="https://user-images.githubusercontent.com/29333817/27004533-bc026662-4e0a-11e7-9bf3-d1a8be5fdd28.png">
![screenshot_20170610_182913](https://user-images.githubusercontent.com/29333817/27004535-c860d286-4e0a-11e7-8cba-9110aee1d123.png)

**Comment by Wuzzy2** [comment]
Yes, a bit. But there is a visible seam in the texture. If you fix this, I'll take this texture.

**Comment by kingoscargames** [comment]
whats a "seam"?

**Comment by kingoscargames** [comment]
could you please just use the mtg model than i could make a separate texture for the front

**Comment by Wuzzy2** [comment]
No, because the MTG model is improper as well. I need a model which is less high to be more MC-like.

**Comment by kingoscargames** [comment]
could you only use it till its replaced?

**Comment by Wuzzy2** [comment]
I rather want to do it right the first time, than to use temporary hacks.
The texture on the side looks strange in the middle, as if there is a cut.

**Comment by kingoscargames** [comment]
a cut?

**Comment by kingoscargames** [comment]
also players should sit in minecarts not stand

**Comment by kingoscargames** [comment]
i cant edit model other than obj without converting them online so i cant really help with models

**Comment by Wuzzy2** [comment]
Alright, I merged your texture with minor adjustments. I will track other cart issues in a new issue.

**Comment by kingoscargames** [comment]
ok
