### ISSUE TITLE
unable to change monsterspawner's mob

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#239]
you should be able to change the mob the spawner spawn with right clicking when wielding a spawnegg

**Comment by kingoscargames** [comment]
from the wiki (http://minecraft.gamepedia.com/Monster_Spawner) :
"The spawned mob can be changed by using a spawn egg on the spawner."

**Comment by Wuzzy2** [comment]
Implemented!
