### ISSUE TITLE
Buttons can't be placed correctly

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#24]
Buttons need a major overhaul, they can't be placed where they should be.

0.10.0

**Comment by WSDguy2014** [comment]
Buttons also should be placed also on floor and ceiling (i think).

**Comment by Wuzzy2** [comment]
Button placement is now a bit better, but might still need some improvement.

**Comment by Wuzzy2** [comment]
Button placement now works like it should.
You can now place buttons only:

* On full cubes
* which are opaque
* and solid
