### ISSUE TITLE
some ores should not be smeltable

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#240]
http://minecraft.gamepedia.com/Emerald_Ore
also diamond shouldnt be smeltable
and coal ore
adn redstone ore
and lapis

**Comment by kingoscargames** [comment]
also diamond shouldnt be smeltable

**Comment by Wuzzy2** [comment]
All of these ores are, in fact, smeltable according to Minecraft Wiki. Closing as invalid.

**Comment by kingoscargames** [comment]
really?

**Comment by kingoscargames** [comment]
oh lol it didnt load in right when i checked
