### ISSUE TITLE
Mobs falling through ground

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#241]
Mobs (so far seen zombies & Endermen) can fall through a single block (usually dirt) even though there is not an opening. The Endermen are not creating an opening by taking blocks.

Just saw the issue with MT 0.4.16 & commit ad6832608706ba1bb094a16f379e227cdc2e52d3
I believe this also happened in MT 0.4.15 & earlier MCL2 commits.

**Comment by kingoscargames** [comment]
i saw that a couple of times and that happens somethimes in mc too (i saw it youtube)

**Comment by Wuzzy2** [comment]
Can you test this also with the stock Mobs Redo mod and maybe report this to the Mobs Redo thread?

**Comment by kwadroke** [comment]
So far no issues with Mobs Redo, but, there's fewer of them to see if there's the same issue.

**Comment by kwadroke** [comment]
Just saw a Husk walk through a door as well.

Using commit 53791c4f9db279f1a416a251e3585cec12e21c11 with a new world.

**Comment by kwadroke** [comment]
When it happens I see this at the console:

`2017-06-10 15:07:29: WARNING[Server]: Pathfinder: failed to update cost map`

**Comment by kwadroke** [comment]
I'm beginning to think it's the Endermen causing the Pathfinder errors. I've been surrounded by zombies, husks & spiders without that error. Then a Endermen comes by and I start getting Pathfinder errors.

**Comment by kwadroke** [comment]
Well might not be Endermen after all, at least directly. 

When I enable Pathdinder debug `#define PATHFINDER_DEBUG` in Minetest (src/pathfinder.cpp) & recompile, I'm seeing this quite a bit with MCL2, and only rarely on Mobs Redo
```
(102,64,43): -
  -Pathfinder: (38,25,-38) not on surface
(103,64,43): -
  -
 44: Pathfinder: (-65,25,-37) current or below is invalid element
(0,64,44): i
  iPathfinder: (-64,25,-37) not on surface
```

**Comment by leorockway** [comment]
I've seen this with zombies a lot in my Skyblock (I actually had to lower the spawning threshold quite a bit there, because mobs were barely spawning, but that's a different issue). I'm going to test vanilla Mobs Redo and report back.

**Comment by kwadroke** [comment]
Mobs are still going though some walls (at least as of last week)

**Comment by rasusmilch** [comment]
Just went looking through the bug tracker. I'm having issues with mobs going through walls as well. Originally spiders were coming through cobblestone walls and attacking me at night. They would "jump" up one block and enter through the second block quite consistently. I "solved" it with lava around my home.

Just recently I attempted to start a farm. Noticed fencing wouldn't keep newborn bunnies and chickens in their pen. Figuring they were small enough to get through the fence I upgraded to 3 high cobblestone walls. The adult and baby chickens and bunny still get out. I also saw a baby cow exit it's pen via glass on the second block up, walk down an aisle between pens, and jump into another pen the same way.

I love the game and effort put into this, but these are pretty frustrating. No idea where to begin in helping with these mods.

Running minetest 0.4.16 on Fedora with git updated to commit 58b9c3dbf5a67b27ed38ee728173e512865847e2.

**Comment by Wuzzy2** [comment]
So I finally managed to find the solution to this bug and fix it! :tada: 

The solution?
Mobs Redo called `setpos` whenever a mob was stuck to displace the mob by a random position. I kid you not! So I just disabled said code as it causes many weird problems.

No idea why this code was there.
