### ISSUE TITLE
the mob/player heads use 17x16/16x17 textures instead of 16x16

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#244]

**Comment by kingoscargames** [comment]
wrong button

**Comment by kingoscargames** [comment]
<img width="912" alt="head steve top" src="https://user-images.githubusercontent.com/29333817/27004791-30576b84-4e10-11e7-8184-d025d106990b.png">

**Comment by kingoscargames** [comment]
i can fix that if you want?

**Comment by kingoscargames** [comment]
oh just the human, creeper and zombie do

**Comment by kingoscargames** [comment]
fixed the textures:
<img width="16" alt="head_creeper_back" src="https://user-images.githubusercontent.com/29333817/27005834-2aec943c-4e27-11e7-899b-7414d8029230.png">
<img width="16" alt="head_creeper_face" src="https://user-images.githubusercontent.com/29333817/27005832-2aeaa528-4e27-11e7-9138-c218fe19e67d.png">
<img width="16" alt="head_creeper_left" src="https://user-images.githubusercontent.com/29333817/27005837-2af1a102-4e27-11e7-9475-fa714be629d9.png">
<img width="16" alt="head_creeper_right" src="https://user-images.githubusercontent.com/29333817/27005833-2aeaaa14-4e27-11e7-9cb2-d97151f48f1a.png">
<img width="16" alt="head_creeper_top" src="https://user-images.githubusercontent.com/29333817/27005836-2aefab86-4e27-11e7-8021-166e03dc5c1e.png">
![head_skeleton_back](https://user-images.githubusercontent.com/29333817/27005835-2aecbd54-4e27-11e7-9f1d-ba9e6b7d8d26.png)
![head_skeleton_face](https://user-images.githubusercontent.com/29333817/27005838-2b00295c-4e27-11e7-9959-5eeb1766a88d.png)
![head_skeleton_left](https://user-images.githubusercontent.com/29333817/27005841-2b01921a-4e27-11e7-85af-24c023d034d3.png)
![head_skeleton_right](https://user-images.githubusercontent.com/29333817/27005839-2b008064-4e27-11e7-8ebd-f678644d33fd.png)
![head_skeleton_top](https://user-images.githubusercontent.com/29333817/27005840-2b010778-4e27-11e7-9038-3ec87d609838.png)
<img width="16" alt="head_steve_back" src="https://user-images.githubusercontent.com/29333817/27005842-2b043c4a-4e27-11e7-97a6-12f92106c320.png">
<img width="16" alt="head_steve_face" src="https://user-images.githubusercontent.com/29333817/27005843-2b04d20e-4e27-11e7-971c-d7d0ca5698b0.png">
<img width="16" alt="head_steve_left" src="https://user-images.githubusercontent.com/29333817/27005845-2b1664ec-4e27-11e7-89b3-4ee38672636f.png">
<img width="16" alt="head_steve_right" src="https://user-images.githubusercontent.com/29333817/27005844-2b16554c-4e27-11e7-855f-44b681b9720a.png">
<img width="16" alt="head_steve_top" src="https://user-images.githubusercontent.com/29333817/27005849-2b1a052a-4e27-11e7-9b5b-7c4872c6bd09.png">
![head_wither_skeleton_back](https://user-images.githubusercontent.com/29333817/27005846-2b17858e-4e27-11e7-89a2-d93cc53b071a.png)
![head_wither_skeleton_face](https://user-images.githubusercontent.com/29333817/27005848-2b18b846-4e27-11e7-980c-65997ce27c02.png)
![head_wither_skeleton_left](https://user-images.githubusercontent.com/29333817/27005847-2b1845be-4e27-11e7-880d-f9629234f2cf.png)
![head_wither_skeleton_right](https://user-images.githubusercontent.com/29333817/27005853-2b333428-4e27-11e7-8f75-eee5ebc557cb.png)
![head_wither_skeleton_top](https://user-images.githubusercontent.com/29333817/27005850-2b2d50e4-4e27-11e7-9165-af3a9d1e7d39.png)
<img width="16" alt="head_zombie_back" src="https://user-images.githubusercontent.com/29333817/27005851-2b2f916a-4e27-11e7-9f48-3828c3d08b97.png">
![head_zombie_face](https://user-images.githubusercontent.com/29333817/27005852-2b311378-4e27-11e7-91e1-84ddc6126e9b.png)
<img width="16" alt="head_zombie_left" src="https://user-images.githubusercontent.com/29333817/27005855-2b348062-4e27-11e7-864a-2f1837284429.png">
<img width="16" alt="head_zombie_right" src="https://user-images.githubusercontent.com/29333817/27005854-2b33c262-4e27-11e7-8f8a-ec031752799c.png">
<img width="16" alt="head_zombie_top" src="https://user-images.githubusercontent.com/29333817/27005856-2b43155a-4e27-11e7-9919-70219fd3f129.png">

**Comment by Wuzzy2** [comment]
Ahhh! You meant the blocks. I thought you meant the actual mobs and players.

**Comment by kingoscargames** [comment]
lol

**Comment by Wuzzy2** [comment]
Fixed in f3fa9b6e4b4f5ecd3d625ca9b27553ee7b221e4b.
Thank you.
