### ISSUE TITLE
mobs attack in creative

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#246]
when i punch/hit a hostile/neutral mob it attacks back even in creative

**Comment by Wuzzy2** [comment]
True story. In the meanwhile, there's simple workaround: You can disable damage as well when you enter Creative Mode, so you don't get killed all the time. In MC, those two settings are linked together anyway.

**Comment by kingoscargames** [comment]
but creepers still blow my stuff up when i hit them :(

**Comment by Wuzzy2** [comment]
Oh, and you can add `only_peaceful_mobs=true` in `minetest.conf`. In current dev, this setting is also available in advanced settings.

BTW: You gave a thumbs down to yourself. :D

**Comment by kingoscargames** [comment]
i gave thumbs down to the creepers

**Comment by kingoscargames** [comment]
in current dev do you mean the current mt 0.4.16 dev?

**Comment by Wuzzy2** [comment]
No, MineClone 2 “unstable” and Minetest 0.4.16 (stable).

**Comment by kingoscargames** [comment]
oh ok now i am sad that i cant update yet :(

**Comment by Wuzzy2** [comment]
Fixed by updating Mobs Redo.
