### ISSUE TITLE
bows don't work in the latest stable release

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#251]
When a arrow hits a mob it wont get damaged.

**Comment by Wuzzy2** [comment]
Sorry, I can't reproduce this bug. :-/

**Comment by kingoscargames** [comment]
i tried shooting  a cow like 9 times but nothing happened

**Comment by Wuzzy2** [comment]
Weird. I can not reproduce this neither in creative mode or normal mode, with any bow strength.

**Comment by kingoscargames** [comment]
Ok

**Comment by kingoscargames** [comment]
I used the newest 0.4.15 compatible version wich should be compatible with 0.4.15 XD

**Comment by kingoscargames** [comment]
it works now after updating to 0.4.16 and the latest dev of this

**Comment by Wuzzy2** [comment]
Well, this is weird. xD
