### ISSUE TITLE
Recipe for chain armor

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#256]
Chain armor was crafted using fire.
in newer versions you cant get fire anymore but i dont know if the recipe is removed

**Comment by Wuzzy2** [comment]
In MC, chain armor can't be crafted, you have to buy it from villagers. Since villager don't work in MCL2 yet, I decided to add a temporary crafting recipe. I'll remove it when villagers finally work.

**Comment by kingoscargames** [comment]
It was craftable with fire.butnnow you cant get.fire
