### ISSUE TITLE
the pig's texture mapping is broken

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#257]
![screenshot_20170611_112838](https://user-images.githubusercontent.com/29333817/27009878-394d42c0-4e99-11e7-8ca3-ef3a81913f5c.png)
![screenshot_20170611_112842](https://user-images.githubusercontent.com/29333817/27009879-394ee8b4-4e99-11e7-98e3-302e65361c54.png)

**Comment by kingoscargames** [comment]
look at the saddle

**Comment by Wuzzy2** [comment]
Fixed in 0.23.0
