### ISSUE TITLE
armorstand bugs

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#260]
when a armorstand is pushed by a piston the armor disappears but players can still place armor it to make it reappear
and when a block falls in it the it breaks and the armor disappears

**Comment by Wuzzy2** [comment]
Okay, fixed. For now.
Pistons are no longer allowed to move armor stands.
When an armor stand is destroyed, it drops its armor.

The real bugfix will be when the armor stand becomes an entity: https://github.com/Wuzzy2/MineClone2-Bugs/issues/70
