### ISSUE TITLE
add wearable pumpkins

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#264]
https://github.com/Wuzzy2/MineClone2-Bugs/issues/66
textures:
![image](https://user-images.githubusercontent.com/29333817/27011150-22db7986-4eb6-11e7-9244-9924eee75200.png)
![image](https://user-images.githubusercontent.com/29333817/27011152-300ceaea-4eb6-11e7-951f-0b58be2563c8.png)

code:
![image](https://user-images.githubusercontent.com/29333817/27011138-ea45ea3e-4eb5-11e7-9f41-c6f30973682a.png)

screenshot:
![image](https://user-images.githubusercontent.com/29333817/27011144-0945b298-4eb6-11e7-93cc-3d65a9b01d59.png)

bug:
![image](https://user-images.githubusercontent.com/29333817/27011146-13aee812-4eb6-11e7-8836-bfe0a6c91520.png)

**Comment by Wuzzy2** [comment]
Pumpkins are now wearable. 6e2f47a1ce3c68187092d0c91d751bd13e3cff6b
For some reason, there were no images visible to me, so I did them by hand.

Thank for your work.

**Comment by kingoscargames** [comment]
pls use this texture a part of it rotated so it looks like mc
![mcl_farming_pumpkin_face](https://user-images.githubusercontent.com/29333817/27011439-b2113eec-4ebb-11e7-912a-934f1841f312.png)

**Comment by Wuzzy2** [comment]
Right. Thanks.
