### ISSUE TITLE
jump over fences with carpets

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#267]
https://www.youtube.com/watch?v=bOjOs56pSIU

**Comment by Wuzzy2** [comment]
Looks like a bug to me. I wonder if I really want to replicate bugs, especially since they might be fixed in Minecraft later anyway.

Besides, I don't see an easy way to re-implement this either. :-/

**Comment by kingoscargames** [comment]
:(

well i will just use the sneak glitch then

**Comment by Gerold55** [comment]
You are supposed to be able to use carpets for on top of fences any creature/mod can't tho only the player.
https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-31336
This was the bug someone reported it's supposed 2 work like that it's a feature

**Comment by Wuzzy2** [comment]
Thanks for digging this one out. Still, not trivial to fix.

**Comment by gejan** [comment]
You could add a "fence top" node, which 
is automatically placed on top of fences
is not walkable (collisionbox of 0.5 height) and 
is buildable to.

If it should only work with carpets you can replace the fence with a smaller version 'on place' of the carpet and reinstall the normal fence 'on dig'.

**Comment by kingoscargames** [comment]
I edited the carpet to make it walkable and that worked but it should have a hitbox of 0x0x0 blocks and still be walkable. :/

**Comment by Wuzzy2** [comment]
This bug has been fixed by making carpets walkable.
