### ISSUE TITLE
non mc wield animation in 0.4.16 (engine change needed)

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#268]
when looking up the item you hold in 1st person moves down
and when looking down it moves up
that doesnt happen in mc 
mt version: 0.4.16

**Comment by Wuzzy2** [comment]
Umm … This basically requires a downgrade of Minetest to version 0.4.15 and I don't think removing this is ever going to happen in Minetest. If you're really lucky, you might convince the developers to add a client setting.

I think I should stop accepting Minetest issues as MCL2 bugs, especially those over which I simply hav no influence over.

**Comment by Wuzzy2** [comment]
Yeah, I'm closing this as a Minetest-only issue. This is purely a Minetest feature request, which will very likely be implemented as a client-side feature, so MineClone 2 will probably never have control over this.

I suggest you go to the Minetest repository.

And the graphical difference is also very, very subtle anyway.

**Comment by kingoscargames** [comment]
ok
