### ISSUE TITLE
grass can be placed on blocks other than grass or dirt

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#269]
![screenshot_20170611_193217](https://user-images.githubusercontent.com/29333817/27013073-07478b2a-4edd-11e7-9bc9-5c1ed4453fae.png)

**Comment by Wuzzy2** [comment]
So … tall grass should have the same placement rules as flowers, right?
The MC Wiki does not state anything about placement restrictions.

In any case, would be an easy fix.

**Comment by kingoscargames** [comment]
i think it should

**Comment by Wuzzy2** [comment]
Yeah, I think it makes sense, simply for consistency's sake. If it turns out to be “wrong”, anyone can feel free to post another issue. :-)

**Comment by Wuzzy2** [comment]
Fixed.
