### ISSUE TITLE
bug with grass paths

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#271]
when i click a grass block from the top nothing happens but when i click on the side it changes into a grass path.

**Comment by kingoscargames** [comment]
also i found that there is a error in the 32x faithful texturepack but that is not a bug that has to do with this

**Comment by Wuzzy2** [comment]
I have no idea what you mean with your 2nd post, but I'll fix the grass path bug no. 1.

**Comment by kingoscargames** [comment]
the second post is not a bug with this, it is a error in the 32x pack

**Comment by Wuzzy2** [comment]
Fixed.
