### ISSUE TITLE
stone, ores and lava generating in flat worlds

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#275]
![screenshot_20170612_162710](https://user-images.githubusercontent.com/29333817/27079133-ccc8c602-5036-11e7-89ab-f4055d6d7394.png)
![screenshot_20170613_123035](https://user-images.githubusercontent.com/29333817/27079132-ccc83638-5036-11e7-86ba-5aa35e300908.png)
![screenshot_20170613_124843](https://user-images.githubusercontent.com/29333817/27079131-ccc4202a-5036-11e7-96a9-b71b78b8d98b.png)
![screenshot_20170613_124943](https://user-images.githubusercontent.com/29333817/27079134-ccca0a08-5036-11e7-81a3-eb12587326ba.png)
![screenshot_20170613_124553](https://user-images.githubusercontent.com/29333817/27079154-df57b9e0-5036-11e7-8663-5a6243a70202.png)

**Comment by kingoscargames** [comment]
i removed  the grass and dirt from a part of the world:
![screenshot_20170613_125907](https://user-images.githubusercontent.com/29333817/27079509-26f62600-5038-11e7-8efa-9aa5d827b2b7.png)
![screenshot_20170613_130000](https://user-images.githubusercontent.com/29333817/27079534-3fa9c9f4-5038-11e7-86f4-85c80f30bec7.png)

**Comment by kingoscargames** [comment]
![screenshot_20170613_130512](https://user-images.githubusercontent.com/29333817/27079694-fbdf4a72-5038-11e7-83e0-eb8839e8daa7.png)

**Comment by Wuzzy2** [comment]
Fixed.
