### ISSUE TITLE
Giant player on boat

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#276]
If a player mounts a boat, the player becomes very large.

**Comment by kingoscargames** [comment]
![screenshot_20170613_140525](https://user-images.githubusercontent.com/29333817/27081591-5f8cf3d2-5041-11e7-902e-20875085767b.png)

**Comment by 22i** [comment]
i think this is because 3d armour player model is huge in blender while boat is small in blender
![player_boat](https://user-images.githubusercontent.com/17874916/27262065-73597db0-544f-11e7-93e8-72ad89e67372.png)

**Comment by kingoscargames** [comment]
maybe make the boat model giant too? XD

**Comment by kingoscargames** [comment]
and with the armor player model?

**Comment by Wuzzy2** [comment]
Fixed in 95d9681b0caddbff0749da2e58fd4ef3e830fb77.
