### ISSUE TITLE
Hand dropped as items on the ground

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#277]
i got a error and couldnt interact with blocks so i closed and reopened the game but when i spawned this happened:
![screenshot_20170613_144604](https://user-images.githubusercontent.com/29333817/27082988-4c7ea82a-5047-11e7-8cc2-30e71e98393d.png)

**Comment by kingoscargames** [comment]
some of them i can pickup but dont get anything, others not

**Comment by kingoscargames** [comment]
now i burnt them with lava

**Comment by Wuzzy2** [comment]
Wait, what? The hand should *never* drop as an item, this is obviously a bug. I have no idea how this could have happen in the first place. :-/

**Comment by kingoscargames** [comment]
Its probably something that has do to with engine

**Comment by kingoscargames** [comment]
I think it was because they werent saved properly when the "cant interact with things and entities behave strange" bug happened and i closed the game i think all items on the ground turned into a "wieldhand".

**Comment by Gerold55** [comment]
Could you look into adding the 3d hand mod into MineClone 2?

**Comment by Wuzzy2** [comment]
This has nothing to do with the issue, but: I won't add this mod, it would add nothing to the game.

**Comment by Gerold55** [comment]
OK I thought you were aiming to make it close to MineCraft that's why I suggested that mod.

**Comment by Wuzzy2** [comment]
No, I simply don't see the point of this mod.

**Comment by Gerold55** [comment]
Oh ok it's so when you change skins you see the hand of the skin properly and it's a 3d model instead of a 2d texture

**Comment by kingoscargames** [comment]
If people want that it is compatible with every subgame (needs a character.png) but breaks rightclicking when i rightclick with my "3d hand" nothing happens

**Comment by Gerold55** [comment]
Oh ok I guess it has something wrong with it on certain subgames works fine for the subgame I use it with.

**Comment by kingoscargames** [comment]
rightclicking on things that arent in default is completely broken when using the mod and also when uninstalling it the hand becomes a unknown item

**Comment by kingoscargames** [comment]
also for some reason when i use that mod it chrashes when looking down

**Comment by Wuzzy2** [comment]
Please open a new issue for new bugs and please describe the bug clearly. I have a hard time following you. :-(

**Comment by kingoscargames** [comment]
I will close this becuase i saw it in one world that doesnt use this.
