### ISSUE TITLE
keeping inventory on death

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#279]
When i die i don't lose my items.

**Comment by kwadroke** [comment]
I've seen this as well.

**Comment by kingoscargames** [comment]
actually there should be a command to toggle that

**Comment by Wuzzy2** [comment]
Argh, crap. This warrants a bugfix release. Fixed.

The `gamerule` command is not implemented, but this setting is indeed now part of the advanced settings. Name: `mcl_keepInventory`.
You can set it in the advanced settings dialog and with `/set mcl_keepInventory <bool>`
