### ISSUE TITLE
32x textures for the doc_identifiers?

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#280]
![doc_identifier_identifier](https://user-images.githubusercontent.com/29333817/27084421-28a2fe56-504c-11e7-9d0f-cfa200eed340.png)
![doc_identifier_identifier_liquid](https://user-images.githubusercontent.com/29333817/27084422-28bf6744-504c-11e7-9196-e84b8553fc02.png) 
these 32x textures look better with all the other 32x32 textures

**Comment by Wuzzy2** [comment]
Not really. The question mark symbols is much harder to see in the hotbar and also has “broken” lines. The outline and question mark also look a bit like “broken lines” to me.

**Comment by kingoscargames** [comment]
Oh yeah the symbol in the "circle" is broken will fix that tomorrow

**Comment by kingoscargames** [comment]
Maybe these: 
![doc_identifier_identifier](https://user-images.githubusercontent.com/29333817/27126620-5616d59a-50f8-11e7-938a-0cfd3060a430.png)
![doc_identifier_identifier_liquid](https://user-images.githubusercontent.com/29333817/27126621-5617917e-50f8-11e7-83a0-6b7414353258.png)?

**Comment by Wuzzy2** [comment]
No, sorry, the question mark is too thin and should be thicker so it can be more easily seen in the hotbar.

**Comment by kingoscargames** [comment]
these:
![doc_identifier_identifier](https://user-images.githubusercontent.com/29333817/27132274-8d17e6fe-510e-11e7-9b6c-1a34c34374ce.png)
![doc_identifier_identifier_liquid](https://user-images.githubusercontent.com/29333817/27132275-8d2031b0-510e-11e7-9100-76dcc4e3b583.png)?
they use the same "?" as now

**Comment by Wuzzy2** [comment]
Okay, those were included, thanks!
