### ISSUE TITLE
Leather armor makes me invulnerable to attacks of endermen

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#285]
But it doesnt block attacks of zombies
So when i use a cheat mod (ubreakable leather armor set) i cant take damage from spiders and endermen
But the "default" leather armor also does that

**Comment by kwadroke** [comment]
I've seen this as well.

**Comment by Wuzzy2** [comment]
This is no longer the case in 0.23.0
