### ISSUE TITLE
Levers models

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#286]
Are you able to use these models for the levers? They need texturing and a little bit of editing though. https://www.mediafire.com/?mazknurst6t3tq6

**Comment by Wuzzy2** [comment]
The mesh has the wrong rotation. It should work with the drawtype `"facedir"`.

As for texturing: Just use the Minecraft default texture as a template. Or a texture of any MC texture pack.

**Comment by Gerold55** [comment]
The way it was setup was like the original mesecons levers I've gotta give it an edit so it sits on the floor again gonna have 2 figure out how to make it so it can be attached to the floor and the wall

**Comment by Gerold55** [comment]
Levers were updated.

**Comment by Wuzzy2** [comment]
Looks better now.
But the lighting on the node looks kinda weird. The top side of the mesh is darker than the sides, different than all the other nodes.
Are you sure you got your normals right?

**Comment by Gerold55** [comment]
I'll look into it and see

**Comment by Wuzzy2** [comment]
I have included the model in MCL2. Levers look now more MC-like!

The problem with the light was indeed a problem with the normals. Some normals were flipped.
But I fixed them. Just remember to get your normals right the next time.

Thank you.
