### ISSUE TITLE
bottom texture for the heads

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#288]
instead of this:
![screenshot_20170617_134432](https://user-images.githubusercontent.com/29333817/27252634-b6848bbc-5363-11e7-8da5-8e7b7737386d.png)
they should have different bottom textures
<img width="16" alt="head_steve_bottom" src="https://user-images.githubusercontent.com/29333817/27252658-599551e2-5364-11e7-9d66-81b364494902.png">
<img width="16" alt="head_zombie_bottom" src="https://user-images.githubusercontent.com/29333817/27252659-59966bcc-5364-11e7-8b71-50f580a55f25.png">
<img width="16" alt="head_wither_skeleton_bottom" src="https://user-images.githubusercontent.com/29333817/27252656-5992b2de-5364-11e7-8e11-13a5e6dd5fb9.png">
<img width="16" alt="head_skeleton_bottom" src="https://user-images.githubusercontent.com/29333817/27252657-59934258-5364-11e7-8030-624305a3aa19.png">
<img width="16" alt="head_creeper_bottom" src="https://user-images.githubusercontent.com/29333817/27252655-5991cb12-5364-11e7-836e-fca94b41a1d7.png">

**Comment by kingoscargames** [comment]
and yes i am working on a mod that ads more armor

**Comment by Wuzzy2** [comment]
Mob head textures have been changed.
