### ISSUE TITLE
Chat Commands

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#289]
Time Set Day
Set Spawnpoint
/spawnpoint

**Comment by WSDguy2014** [comment]
How about /fill command, that will be useful for creative builders.

**Comment by Gerold55** [comment]
Also is it possible 2 map a key button to be able 2 select a block or shift click 2 pick a block?

**Comment by Wuzzy2** [comment]
Duplicate of #32.
