### ISSUE TITLE
leggings and boots are mirrored wrong

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#290]
![image](https://user-images.githubusercontent.com/29333817/27262852-72c4aad6-545f-11e7-9c16-1f840b95c4ed.png)

**Comment by kingoscargames** [comment]
Actually the the textures for the boots are on the leggings' layer

**Comment by Wuzzy2** [comment]
There has been a complete texture pack change. Please tell me if this issue still applies.

**Comment by Wuzzy2** [comment]
Old bug, no response.
