### ISSUE TITLE
Hopper has an extended collusion (and model) off block a little bit

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#294]
This hopper acts like a stair.
![image](https://user-images.githubusercontent.com/13905392/27396780-d9dfa5e0-56bc-11e7-96a3-fcccaefa922f.png)
Compare to original Minecraft does not have an extended thing.

MineClone 2 subgame version: 0.22.2

**Comment by kingoscargames** [comment]
wow you live at bedrock? XD

**Comment by kingoscargames** [comment]
but you are right

**Comment by Wuzzy2** [comment]
Fixed in 0c04a958c3d1468b050d50e7a5f98cc78c90a143.
