### ISSUE TITLE
hopper looks weird

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#296]
![screenshot_20170621_194757](https://user-images.githubusercontent.com/29333817/27398749-026a3ee6-56bb-11e7-8ddd-c51c15352b57.png)
it uses the top texture for the side

**Comment by Wuzzy2** [comment]
The bug was that the spigot extended out of the node borders. This should not be the case, and I shortened the spigot.
It should be fixed now.
