### ISSUE TITLE
preview textures for the chestplates look weird

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#297]
![screenshot_20170621_195539](https://user-images.githubusercontent.com/29333817/27398953-a2994af6-56bb-11e7-8d79-5352560369f1.png)
the arm parts shouldnt be directly on the players arm
but more like this:
![screenshot_20170621_193028](https://user-images.githubusercontent.com/29333817/27399138-16e66556-56bc-11e7-91b3-35dc03a5fa86.png)

i made some new textures for them:
![3d_armor_chestplate_chain_preview](https://user-images.githubusercontent.com/29333817/27399168-2d5e11f8-56bc-11e7-9c73-5b4970306dbd.png)
![3d_armor_chestplate_diamond_preview](https://user-images.githubusercontent.com/29333817/27399165-2d53998a-56bc-11e7-9339-a0cefe039d58.png)
![3d_armor_chestplate_gold_preview](https://user-images.githubusercontent.com/29333817/27399167-2d56f24c-56bc-11e7-8e9e-2bb2b02c2f53.png)
![3d_armor_chestplate_iron_preview](https://user-images.githubusercontent.com/29333817/27399166-2d53c446-56bc-11e7-9b33-659451dd7a48.png)
![3d_armor_chestplate_leather_preview](https://user-images.githubusercontent.com/29333817/27399164-2d508c4a-56bc-11e7-9125-ae581dad9cb7.png)
(they are also smaller files)

**Comment by Wuzzy2** [comment]
Please stop filing texture bugs. I want to replace all textures with an entirely different 16×16 pack eventually.
