### ISSUE TITLE
Lever

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#3]
* [ ] Put on floor
* [ ] Mesh-based model
* [ ] Put on roof

**Comment by tobyplowy** [comment]
> Put on floor

And roof

**Comment by tobyplowy** [comment]
I ment ceiling not roof It means the same Thing but Still Just so there is no confusion

**Comment by Wuzzy2** [comment]
Basic lever implementation is done.
Details are tracked in #353.
