### ISSUE TITLE
Trees grow too fast.

### ISSUE THREAD

**Issue by maikerumine** [Wuzzy2/MineClone2-Bugs#303]
Compared to latest Minecraft

**Comment by Wuzzy2** [comment]
How fast are saplings supposed to grow? The Minecraft Wiki does not provide a lot of information.

**Comment by Wuzzy2** [comment]
Is the sapling growth speed better now?

@maikerumine

**Comment by Wuzzy2** [comment]
No reaction for 25 days. I think the growth speed is OK. Closing …
