### ISSUE TITLE
Replace mobs_mc with maikerumine's version

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#307]
https://github.com/maikerumine/mobs_mc

TODO:
* Replace mod
* Integrate items
* Double-check this major change does not accidentally summon Cthulhu

**Comment by maikerumine** [comment]
I'll do some testing today. :)

**Comment by leorockway** [comment]
Make sure that Ph'nglui mglw'nafh Cthulhu R'lyeh wgah-nagl fhtagn.

Oh... I think I might've broken the third part of your To Do.

**Comment by Wuzzy2** [comment]
Fixed.
