### ISSUE TITLE
Faithful is nonfree

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#308]
I didn't want to hijack the issue in mc_mobs, so I opened this one.

Here's the parts of Faithful's disclaimer [0] that I believe make it nonfree:

```
It's fine for people to use stuff from the Faithful 32x32 pack so long as guidelines bellow are followed.
Requirements:
- No money making links.
Finally:
- If I decide I don't want you using stuff from the pack then that is final. This will only be the case in unusual circumstances.
```

I'm not sure what kind of free you're aiming for, but those two make it very nonfree in my mind (I usually equate free with some version of GPL / CC BY SA).

[0] http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1223254-faithful-32x32-pack-update-red-cat-clay-1-8

**Comment by leorockway** [comment]
I just noticed that this Faithful and the other Faithful are not the same. The other one is called Faithful Vanilla and it seems free to me.

**Comment by leorockway** [comment]
Actually, Faithful Vanilla is a fork of Faithful. So the nonfreeness might still be a issue.

**Comment by leorockway** [comment]
About Jolicraft not having a license, this is what I found on the website:

`I don't mind if you use any of my textures, help yourself and enjoy! But I just ask that if you do use something I've made that you state somewhere in your thread what you used of mine, and include a link to jolicraft.com or my thread via the Jolicraft logo (http://www.jolicraft.com/images/logo.png).`

**Comment by Wuzzy2** [comment]
God damn it! This makes getting rid of Faithful Vanilla even more important. 

Closing this. Continue discussion in #76.
