### ISSUE TITLE
Possible crash when using corner stair (and posibly other nodes) near unknown nodes

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#309]
If you place stairs/corner stairs near unknown nodes, it crashes.

In general, MCL2 doesn't like it if there are unknown nodes. Needs more testing.

For reference: https://github.com/maikerumine/mobs_mc/issues/36

EDIT: Other possible crash: Unknown item inside flowing water.

**Comment by maikerumine** [comment]
Quick fix:

in functions in core items, add this line

		local d = minetest.registered_nodes[n.name]
		--====
		--====
		--====
		if not d then
			return false
		end
		--====
		--====
		--====

**Comment by Wuzzy2** [comment]
There were many crashes with unknown nodes, which should be fixed now.

Thanks for kicking me in the ass. This bugfix has been delayed far too much.

**Comment by maikerumine** [comment]
Yay!!! :). This is big victory for mc2.
