### ISSUE TITLE
Add handy=1,shovely=1, to Mobs_MC or add Choppy, crumbly to Mineclone2 nodes

### ISSUE THREAD

**Issue by maikerumine** [Wuzzy2/MineClone2-Bugs#310]
For forward compatibility

**Comment by Wuzzy2** [comment]
Please ignore MineClone 2 for now. When I start to integrate the new `mobs_mc` into MineClone 2, I will do all of the integration work by myself. It will actually be quite easy.
Please don't bother adding groups or any special support into the original mod; it is not required and is just a waste of time.

**Comment by maikerumine** [comment]
Well then hurry!! :)
