### ISSUE TITLE
Change unknown node texture to "update!" and rename to "Info update".

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#314]
In Minetest if you enable a mod that adds more blocks, build a block that has a mod, disable mod and rejoin world, now you can able to see an unknown node. If you break unknown node, will drop unknown item (that's not supposed to be, it doesn't exist in Minecraft), you almost cannot able to drop. If you enable a mod that adds animals and monsters for example, find an example animal, disable mod and rejoin world, now you can able to see a missing entity called "unknown object" (another feature was not supposed to be, it doesn't exist in Minecraft), it sometimes moves non-stop, goes through blocks and kills instantly with one punch. It's like a 3D model of missing model says "ERROR" from some games running on Source engine. But in Minetest is 2D particle for entities.

But in Pocket Edition of Minecraft there is 2 blocks, which is "update" and "ate!upd" block, more than 1 in Minetest. Should add a new missing block for "ate!upd" block. Converting many unknown nodes with a checkerboard pattern using 2 new blocks. For unknown objects and item should be detecting and removing completely. More information about info update block here: http://minecraft.gamepedia.com/Pocket_Edition_unused_features#info_update

Speaking about texture changes here is 2 unobtainable items. air and ignore blocks has an additional 
inventory texture for exclusive in version 0.4.16. Previously in version 0.4.15, the texture for air and ignore blocks shows a inventory texture called "unknown node". But in Minecraft at snapshot version 13w38b, air inventory texture has a missing texture look like this:

![image](https://user-images.githubusercontent.com/13905392/27772320-4cf0a364-5f68-11e7-9811-c7ac4f4c935d.png)

(just like other games running on Gold Source and Source engine) and actually holding air block.

I don't know if you not going to add a new block and changing textures and feature in the next version, that will be sad. :(

**Comment by Wuzzy2** [comment]
So … what exactly do you want?

Air and ignore textures are here to stay (probably). Replicating overly technical features of Minecraft is clearly out of scope for this project.
Same with unknown nodes, items and objects. These things go deeply into the Minetest engine, and I see no point in changing this (too much work for no real benefit).

I might be OK in changing the textures however, but not if they are ambigious.

**Comment by kingoscargames** [comment]
In mc it looks like this: ![image](https://user-images.githubusercontent.com/29333817/27820837-794a5bd8-60a0-11e7-9cca-9164013d0192.png) ,right?
I don't know what "ignore blocks" are but this texture: "![image](https://user-images.githubusercontent.com/29333817/27820925-ba9a2762-60a0-11e7-9302-454f322a7167.png)" (it is really small) should be used for air.

**Comment by kingoscargames** [comment]
It should look like this right? :
![screenshot_20170704_102736](https://user-images.githubusercontent.com/29333817/27821724-9a389ece-60a3-11e7-8da7-546f13db73cf.png)
It can't be 3D i believe because it would need a different wield block.

**Comment by kingoscargames** [comment]
![screenshot_20170704_104910](https://user-images.githubusercontent.com/29333817/27822600-748bfeac-60a6-11e7-9bdd-3f48e5904a93.png)

**Comment by Wuzzy2** [comment]
Okay, I won't use these textures as they are ambigious, and I think Minetest's default textures make more sense.
MCL2 uses custom textures anyway, so this decision is consistent.

Feature request rejected.

**Comment by WSDguy2014** [comment]
@kingoscargames unknown block texture is must be for "update!" block with dirt background, are you trying to ignore that for Pocket Edition one?

**Comment by Wuzzy2** [comment]
The word “update” would be misleading for Minetest because there are many reasons for unknown nodes. Probably most common reason is that you simply disabled a mod.
