### ISSUE TITLE
Slimes floating (Subgame version 0.23.0)

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#321]
![screenshot_20170707_115707](https://user-images.githubusercontent.com/13905392/27950915-c30c70fe-630b-11e7-806e-cdbce7f29538.png)

**Comment by kingoscargames** [comment]
That's because of the model it has a translucent layer but that is not supported by the engine yet(i believe).
Also i think this should be reported in: https://github.com/maikerumine/mobs_mc/issues

**Comment by kingoscargames** [comment]
yeah it is missing the translucent layer: 
![slime](https://user-images.githubusercontent.com/29333817/27952325-261e7cea-6308-11e7-8ed4-f0d4dc19c203.png)

**Comment by Wuzzy2** [comment]
I changed the slime texture:
![New slime](https://i.imgur.com/MvambuV.png)

New texture is 100% opaque, the effect is just done by a simple overlaying.
