### ISSUE TITLE
Placing sapling don't make sounds

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#322]
Even can plant on any block
![screenshot_20170707_141205](https://user-images.githubusercontent.com/13905392/27955633-6957fa70-631e-11e7-952c-35241fd31ab5.png)
Tested in subgame version 0.23.0

**Comment by kingoscargames** [comment]
oh yeah i forgot to report this

**Comment by Wuzzy2** [comment]
Fixed. Sounds work now. And saplings now can only be planted on grass block, dirt, podzol.
