### ISSUE TITLE
the zombie head is missing the overlay(the "armor" textures)

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#323]
like i said in: https://github.com/maikerumine/mobs_mc/issues/89 zombies have a "hat" layer and the armor textures are missing it: 
![image](https://user-images.githubusercontent.com/29333817/27956573-c02abc06-631a-11e7-870a-475d39696019.png)
maybe use these textures? :  
<img width="32" alt="mcl_heads_zombie" src="https://user-images.githubusercontent.com/29333817/27956640-01de8ba0-631b-11e7-9e2d-00c9eee9d6ba.png">
<img width="8" alt="mcl_heads_zombie_preview" src="https://user-images.githubusercontent.com/29333817/27956639-01de5356-631b-11e7-94b5-2aecebdda75e.png">

**Comment by Wuzzy2** [comment]
Fixed since quite a while now. I just forgot this issue. XD
