### ISSUE TITLE
bow changes texture

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#325]
![screenshot_20170707_192841](https://user-images.githubusercontent.com/29333817/27969284-90473566-634a-11e7-9ea1-5313132aed4e.png)
look at the hotbar the bow changes texture when right clicking 
EDIT: i meant when rightclicking for the second time the bow changes to the 32x32 texture

**Comment by WSDguy2014** [comment]
I remember played on 2B2T MineClone 2 Minetest server, bow and arrow texture is changed, there is different meta data for items, for example slime ball, cannot be crafted into slime block. Rotten flesh is also different meta data, if you eat, it will instant lose hunger points, than hunger effect. Currently, server still using a MineClone 2 subgame version 0.22.3

**Comment by Wuzzy2** [comment]
Do you have still the `mobs_mc` mod manually enabled? You must now disable it, otherwise there will be conflicts with `mobs_mc` which is included in MCL2.

**Comment by kingoscargames** [comment]
hmmm i dont know what the problem was but when i removed the mod and copied the downloaded version again it was fixed

**Comment by kingoscargames** [comment]
I think i know what the problem was now , there were some missing texture so i copied the textures from the mod and it also had the bow textures. LOL
