### ISSUE TITLE
Ice should turn to water when broken

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#326]
I believe that breaking an ice block should turn it into water. From the MC wiki:

` Ice is very similar to Snow, in the sense that it melts when it comes into close proximity of Fire,a Torch, or Lava. Ice is not affected by fire, but when melted with lava, it will produce Water. This will also happen if ice is destroyed and there is a block beneath it.`

**Comment by Wuzzy2** [comment]
Done in 4802b7320c95170518fb6608f9eb0e8ccb86e0ad.

**Comment by kingoscargames** [comment]
lol, I was replacing all the ice in my world with water (in survival!)
