### ISSUE TITLE
witch breaks blocks

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#329]
i was in a cave with water and when i tried to swim up i got attacked ye a witch and then he/she threw some potions at me and then a water block: 
![screenshot_20170710_173241](https://user-images.githubusercontent.com/29333817/28026270-d3c1cd5e-6595-11e7-9b1f-c55ff7363c27.png)
![screenshot_20170710_173250](https://user-images.githubusercontent.com/29333817/28026283-dd067428-6595-11e7-8452-48630b19f5c3.png)
edit: *by

**Comment by kingoscargames** [comment]
a witch tried to enter my house and when i wanted to open the door i saw this: 
![screenshot_20170710_174329](https://user-images.githubusercontent.com/29333817/28026806-6f2ed150-6597-11e7-82ce-aa7bcfb224c7.png)

**Comment by kwadroke** [comment]
I've also seen the water blocks when dealing while attacking witches them under water.

**Comment by kingoscargames** [comment]
![screenshot_20170711_141424](https://user-images.githubusercontent.com/29333817/28067873-5cc091a0-6643-11e7-8612-dcc47751f049.png)  it dropped grass 
(also they replace F*CKING BEDROCK with dirt)

**Comment by Wuzzy2** [comment]
Fixed.
