### ISSUE TITLE
Dirt with grass looks weird with non-default texture

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#331]
If I switch the texture from the Minetest texture tab I see that the dirt part of the dirt with grass block doesn't render correctly. It looks black or transparent. I can post a picture if needed.

**Comment by Wuzzy2** [comment]
Well, you need to be a MCL2-compatible texture pack first.
If the texture pack is not compatible with MCL2, you can't use it.

**Comment by leorockway** [comment]
Is there documentation on how to make a compatible texture or should I read your code to figure it out? I'd like to maybe take a stab at a MC conversion script. If there's no documentation i could help with that.

**Comment by kingoscargames** [comment]
the default texture is a overlay

**Comment by Wuzzy2** [comment]
No documentation is available so far. Most textures can be used verbatim, but some exceptions apply. I will slowly add documentation for these exceptions.
