### ISSUE TITLE
3 Watermelon plants, 1 melon

### ISSUE THREAD

**Issue by leorockway** [Wuzzy2/MineClone2-Bugs#333]
I have 3 watermelon all next to one block. When watermelon grows it's linked to all 3 stems. The expected behaviour would be for the watermelon to only belong to one plant and for each plant to grow its own watermelon. This might also happen to pumpkin, but I can't cofirm it yet. I'll add another comment once I see (or fail to see) the same behavior.

**Comment by Wuzzy2** [comment]
Invalid. This is expected behaviour. Quoting <http://minecraft.gamepedia.com/Melon_seed>:

> If a melon is already occupying an adjacent dirt/grass or farmland spot, the stem will not grow any more melons until the melon is removed.

> A fully-grown single stem will connect to any melon in an adjacent square, thus there are 5 possible appearances to a stem. If there are multiple melons it can connect to, it will favor the east, then west, north, and south. When the melon is removed, the stem will return to its straight shape.
