### ISSUE TITLE
Lower level axes are useless.

### ISSUE THREAD

**Issue by kaeza** [Wuzzy2/MineClone2-Bugs#34]
Not sure if this is already reported in the forum topic.

Punching down trees is faster than using wooden and even stone axes.

Wooden axes in Minecraft are *slightly* faster than the hand (to the point of being useless there too), but there is a notable difference between the hand and a stone axe.

Currently at kaeza/MineClone2@9ea2c77fdfbe2b8ddb9412ff7511c0643bad3c0e "Fix bad enter key handing in craftguide".

**Comment by Wuzzy2** [comment]
Confirmed.
Duplicate of #7.

**Comment by kaeza** [comment]
Ah sorry.

**Comment by Wuzzy2** [comment]
This is now fixed.
