### ISSUE TITLE
Pressure plates send rapid-repeted signal

### ISSUE THREAD

**Issue by GreenXenith** [Wuzzy2/MineClone2-Bugs#343]
Standing on a pressure plate will have an infinite-rapid-fire signal.
Example:
1) do /giveme mcl_throwing:arrow -1
2) Place dispenser facing sideways
3) Put arrows in dispenser
4) Place pressure plate next to dispenser
5) Stand on plate
6) Have fun
7) Wonder why it works like a machine gun
-Also works with noteblocks and doors ;D

**Comment by Wuzzy2** [comment]
Fixed.
