### ISSUE TITLE
Redstone torch bugs

### ISSUE THREAD

**Issue by azekillDIABLO** [Wuzzy2/MineClone2-Bugs#351]
also related to #350

I noticed that some redstone features were missing

- place a block with a button on it's side and a redstone torch at the opposite:
    - if you press the button it works fine, torch turns off and lights up after that (with a big delay though)
    - but if you place the button on the side of the block, nothing happens

- also this shouldn't happen in this way, the top torch should be off and the bottom one lit: 
![screenshot_20170731_140404](https://user-images.githubusercontent.com/17685062/28781308-ef1d47c0-7609-11e7-8751-baa2c45a63f1.jpeg)

**Comment by Wuzzy2** [comment]
All of these bugs are fixed now!
