### ISSUE TITLE
Banner turns black when overlapping with opaque node at bottom

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#354]
![screenshot_20170801_195942](https://user-images.githubusercontent.com/29333817/28839540-4a25b59a-76f4-11e7-85d1-ed9f3ddfa895.png)

**Comment by Wuzzy2** [comment]
Not exactly true. It turns normal when 2 nodes below the top part of the banner are empty.
Only if one of them is occupied, it gets black.

Still a valid bug report. Quite annoying, it's partially a MT bug because entities turn black when they collide with nodes.

**Comment by azekillDIABLO** [comment]
> I can find a workaround by restricting banner placement.

Why not just moving the entity a bit? Make it a bit farther fform the wall and/or put a smaller selection box. it should work! :smile:

**Comment by Wuzzy2** [comment]
Related Minetest issue: https://github.com/minetest/minetest/issues/2467

@azekillDIABLO: The mesh is too tall.

**Comment by Wuzzy2** [comment]
LOL.
I just tested hanging banners Minetest 0.4.16-dev (commit ID: a4048e4e2e6d3c9177270437687118b93c33bf77).

And they **work**! The shading issues have been fixed there.

So I guess you just need for the next Minetest release and should be fixed. I close issue as being solely a Minetest bug.

I won't do the workaround as I said earlier, I don't think it is worth it.
