### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#356]
Am working on new textures need some help will add link to them ASAP

**Comment by azekillDIABLO** [comment]
i'd like to help :call_me_hand:

**Comment by Wuzzy2** [comment]
If you want to help, check out issues with the labels “graphics” and “help wanted”.

Here's a link:
https://github.com/Wuzzy2/MineClone2-Bugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20label%3Agraphics

I close this now as this issue does not have any actual content. :stuck_out_tongue:
