### ISSUE TITLE
Ocelot spawns

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#360]
I've been away for a while, but just loaded up 0.26.0 and noticed a problem with Ocelot spawns. Currently they are spawning everywhere in MineClone2, but they should be restricted to spawning in jungle biomes.

**Comment by leorockway** [comment]
Depends on https://github.com/minetest/minetest/issues/3685

**Comment by Wuzzy2** [comment]
Fixed by workaround.
Ocelots now spawn only on jungle wood, jungle leaves, ferns and podzol. All of which should ever only occour in jungles naturally.
