### ISSUE TITLE
Dungeon spawners

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#361]
In 0.26.0 I noticed that placing a torch on and/or around a dungeon spawner doesn't disable the spawns of a dungeon spawner. Usually when a torch is placed on or near a spawner, the light from the torch stops the spawner from spawning more mobs.

**Comment by leorockway** [comment]
Duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/221
