### ISSUE TITLE
Void doesn't kill player if damage is disabled

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#364]
If the player falls into the void with damage disabled, nothing happens.

**Comment by kingoscargames** [comment]
Its not really a bug but more a missing feature, because why would it damage players if damage is disabled?

**Comment by Wuzzy2** [comment]
It's a bug because this means the player will just fall into the void forever with no way to respawn. This is worse than death. The players must die so the game can keep going.

An alternative solution would be to just teleport players like in a respawn.

In MC, the deep void always hurts you no matter what and I think this just makes complete sense for the above reasons.

**Comment by Wuzzy2** [comment]
If you're in the deep void with damage disabled, you now just teleport back to spawn, so you're not stuck in the void forever.
