### ISSUE TITLE
Merge mcl_stairs and mcstair

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#370]
To make adding stairs more straightforward.

**Comment by Gerold55** [comment]
Also needs a better system to add cornered stairs. Am only able to angle a stair one way not the other way.

**Comment by Wuzzy2** [comment]
Mods have been merged. `mcstair` is now gone.

API has been cleaned up and documented. Adding stairs is now straightforward.
