### ISSUE TITLE
Players terribly sitting on horse, bad horse control and invisible armor relog-in

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#38]
![screenshot_20170219_203310](https://cloud.githubusercontent.com/assets/13905392/23105163/19ddd00c-f6e3-11e6-92d3-15a57fd5026b.png)

If you on full set iron (for example), re join world, armor will turn into invisible, needs to re put back in, to make it visible again.

Horse turning control must be on mouse, instead of "A" and "D" keys, "A" and "D" keys uses for strafe walk.

This is on subgame version 0.10.0

**Comment by Wuzzy2** [comment]
Confirmed. Horses are terribly broken indeed and need a major rework.

**Comment by Wuzzy2** [comment]
Armor bug fixed.

Horses have been removed because they were eternally broken. I plan of course re-introduce them later.
