### ISSUE TITLE
grass with snow has odd lines

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#380]
look at the line on the snow with grass and than look at the normal grass with dirt
![snow bug](https://user-images.githubusercontent.com/16853304/29716011-f970f1fa-89a9-11e7-8d50-7dbb11df74dc.png)

this may be becouse i have a high resolution screen 1920x1080 or it is a minetest engine problem
it doesent happen in minetest game
![snow bug](https://user-images.githubusercontent.com/16853304/29716186-b2957674-89aa-11e7-8f5b-e211dbda3f0d.png)

**Comment by kingoscargames** [comment]
This happens sometimes in minetest_game for me too. (but with stone instead of dirt with snow)

**Comment by Wuzzy2** [comment]
Please report a bug in Minetest, this looks like a typical rendering mistake.
The node definitions look fine, it is unlikely this bug is caused by MCL2.
