### ISSUE TITLE
Make endermen less aggresive

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#382]
Make endermen less aggressive. They are way too evil right now.

**Comment by leorockway** [comment]
Somewhat related to https://github.com/maikerumine/mobs_mc/issues/106

**Comment by Wuzzy2** [comment]
Endermen are now passive by default like zombie pigmen. They now attack only if provoked.

Note that looking at them is (not yet) a provocation.
