### ISSUE TITLE
"Hay Bale"  should reduce fall damage

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#386]
> Falling onto a hay bale reduces the fall damage by 80%, meaning whatever falls on a hay bale only takes 20% of the normal fall damage.
An unarmored player with full health and no effects can fall as far as 100.27 blocks onto a hay bale, and still survive with 1health remaining.

**Comment by Wuzzy2** [comment]
Fixed!
