### ISSUE TITLE
Portal textures are the same as in mc 

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#387]

**Comment by Wuzzy2** [comment]
Fixed! Replaced with a dummy texture. A quality texture need to be added later.

**Comment by kingoscargames** [comment]
The end portal texture should also be hanged.

**Comment by Wuzzy2** [comment]
Yeah, but it isn't a copy from MC.

Compare:  https://minecraft.gamepedia.com/media/minecraft.gamepedia.com/thumb/8/8e/Active_End_Portal.png/800px-Active_End_Portal.png?version=cc47842fee29d2ace4c3389a425f05f9

**Comment by kingoscargames** [comment]
The texture is in the 1.10 default textures though.

**Comment by Wuzzy2** [comment]
OK. I used a new texture. The old texture needed updating anyways. Not the prettiest texture but the End is WIP anyway.
