### ISSUE TITLE
Friendly mobs (animals) get stuck on trees

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#389]
Might be more of a mobs_mc issue, but, horses, pigs, sheep, & cows (at least) seem to get stuck on a tree as it's walking when their heads hit it. 

Tested on commit 916bf70b8542cf891cd8aa45ae1a6eb056effb16 if I remember correctly.
I have multiple screen-shots that I can upload tonight if it will help.

**Comment by Wuzzy2** [comment]
This is partially intentional. Many mobs are afraid of heights and don't want to walk off cliffs which are deeper than 4 blocks.
If a mob refuses to walk at all because of this, this is intentional.

Minetest's pathfinder seems to be broken. I don't think I fully understand your problem.

**Comment by kwadroke** [comment]
This issue is not a cliff problem. It happens on level ground.
My guess is that pathfinding doesn't know how to handle trees so they continue to try to walk through them instead of turning to avoid.

**Comment by Wuzzy2** [comment]
Yeah, pathfinding in MT is not very smart, sadly. :-(

**Comment by rasusmilch** [comment]
Yes... I see that pathfinding is QUITE broken. The animals in a pen just jump repeatably against the walls, and won't detect openings or better slopes. Quite sad really. Does there not exist a smarter algorithm? I'm a simple CS graduate but would think there would be ready-to-go libraries for these things for decades (I plead ignorance.)

**Comment by Wuzzy2** [comment]
Looks fixed after upgrade to Mobs Redo 1.41.

If you still think this is a problem, post a new issue with more detailed description and maybe even screenshots.

**Comment by Wuzzy2** [comment]
Pleae proceed here:
https://github.com/Wuzzy2/MineClone2-Bugs/issues/476
