### ISSUE TITLE
Missing boat textures

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#39]
White/no textures for all boat types:
![screenshot_20170219_205651](https://cloud.githubusercontent.com/assets/13905392/23106915/6333af64-f6fd-11e6-9bbe-75ccfaf15d45.png)

Subgame version: 0.10.0

**Comment by Wuzzy2** [comment]
Confirmed.
But PLEASE post only one issue per bug, not 3 in one. It is very confusing.

**Comment by tobyplowy** [comment]
@Wuzzy2 before you add the boat (I will first have to check the mapping on the model 22i made)

**Comment by Wuzzy2** [comment]
OK.

**Comment by tobyplowy** [comment]
@Wuzzy2 use this model for the boat (its the model 22i made but fixed) NOTE the paddels need to move if you move forward and stay like they are if not moveing

[boat.zip](https://github.com/Wuzzy2/MineClone2-Bugs/files/788040/boat.zip)

**Comment by Wuzzy2** [comment]
Boats finally have textures now!
bdc541b01e95048eb8e8bef89b8003da2c739bf7
