### ISSUE TITLE
Squid model size is too small?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#392]
![screenshot_20170909_202002](https://user-images.githubusercontent.com/13905392/30242512-6b3fd9ca-95a0-11e7-86b3-f640c106d303.png)

Subgame version: 0.28.0

**Comment by Wuzzy2** [comment]
How big should it be?
According to MC Wiki, squids are very small (0.8×0.8 blocks).

**Comment by WSDguy2014** [comment]
Hmm, i didn't notice difference, the older version of Minecraft, the size is bigger than latest version of the Minecraft one. I have to close the issue, i don't know. Because it's a feature...
