### ISSUE TITLE
Entering the Nether for first time, an glitched exit portal spawned.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#396]
Before entering the nether.
![screenshot_20170911_193756](https://user-images.githubusercontent.com/13905392/30286120-23ce74f4-9729-11e7-92f4-58df1f4911a9.png)
After entering the nether.
![screenshot_20170911_193956](https://user-images.githubusercontent.com/13905392/30286149-34d4fdc2-9729-11e7-9155-29559030429f.png)
It's still can be teleported back to overworld.

Tested in 0.28.0

**Comment by Wuzzy2** [comment]
This should be fixed now. Note that Nether portals are still not perfect yet and need more work to be really MC-like.
