### ISSUE TITLE
Rivers have riverbed out of grass blocks in valleys mapgen

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#398]
I have no idea why this is happening. I have set `node_riverbed` and `depth_riverbed` for all biomes, yet in many biomes the rivers in the valleys mapgen still generate with grass blocks as riverbed instead of sand. Even worse, trees generate in the rivers, probably because it's made of grass blocks. Very weird.

@paramat: What could possibly be the cause for this? Are you aware of any problems in the valleys mapgen with regards to riverbeds?
I have also seen the same bug in Lord of the Test.

**Comment by paramat** [comment]
I've seen this happen sometimes but can't remeber the cause or solution, will investigate your code.

**Comment by Wuzzy2** [comment]
@paramat: I think I figured out the reason!
I currently use the default water (`mcl_core:water_source`) for both ocean water and river water.
Apparently Minetest seems to get confused when I do that.
This node has a liquid flowing distance of 7 (instead of the default 8).

If I add a new separate river water node, and use that for the rivers instead, the riverbeds are generated correctly. But I'm not sure if I want to add a new node.

**Comment by paramat** [comment]
Sorry i didn't investigate. Yes riverbed nodes are only placed if river water is detected above the river bed. You could set the 'river water' mapgen alias to the normal water node.

**Comment by Wuzzy2** [comment]
Sorry, this solution is too hacky.
First, I don't like to add a node only to make the mapgen happy.
But this is only a minor problem:
Adding the node definition is simple, but handling all the special cases I have to capture now is not.
The biggest problem is that this fake river water won't merge with normal water, and water flowing will appear to the player to be completely messed up.

If the mapgen *depends* on the river water node to be different, then it's a design flaw. Using the same node for river water and normal water is a perfectly reasonable use case.

**Comment by paramat** [comment]
> First, I don't like to add a node only to make the mapgen happy.

Too bad, it's necessary due to how mapgen has to work.

> The biggest problem is that this fake river water won't merge with normal water, and water flowing will appear to the player to be completely messed up. For example, if the player empties a “normal water” bucket near a river.

Good point, in the issue thread i suggest we can add code to buckets that allows liquid A to drop liquid B, similar to and consistent with the 'drop = ' node definition. This will be useful for other uses.

> If the mapgen depends on the river water node to be different, then it's a design flaw.

No, i explain why in one of your issues.

> Using the same node for river water and normal water is a perfectly reasonable use case.

It seems reasonable at first if you don't know about the resulting flooding risk and how mapgen works. If river water could have used normal water it would do so already, adding a new 'base terrain node' is a big step that required a lot of justification.

**Comment by Wuzzy2** [comment]
I have now added river water to this subgame, fixing this issue.

After many months, I have finally decided to no longer try to be 100% strict in cloning Minecraft. After all, this seems to be the more sensible solution.
