### ISSUE TITLE
Sun and Moon textures are Slightly blurry

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#40]
@Wuzzy2 this is probably a minetest issue because I also have this problem with my own sub game (note I have no custom settings so that's not the problem)

**Comment by Wuzzy2** [comment]
:-(
Confirmed.

**Comment by tobyplowy** [comment]
You can make an issue on the mintest github page to request a fix

**Comment by Wuzzy2** [comment]
Fixed in f10b7127522590c8aab76bc9112cbd1f75e6fb03.
