### ISSUE TITLE
Stones don't drop items anymore

### ISSUE THREAD

**Issue by mgo79** [Wuzzy2/MineClone2-Bugs#400]
minetest 0.4.16 win64
mineclone2 0.29.0

clean istall, no mods

If you mine stones (stone, granite, coal, ...) or ice, they don't drop items.
Sand, wood, dirt etc do drop items...

**Comment by Wuzzy2** [comment]
Works as intended. If you mine stone with hand only, it doesn't drop anything, you need a wooden pickaxe at least.

Take a look into the block's help entries or use the unique lookup tool to learn what tools are required to mine the block correctly. Or just figure it out on your own.
