### ISSUE TITLE
Too many sugar canes

### ISSUE THREAD

**Issue by Greentaily** [Wuzzy2/MineClone2-Bugs#403]
I don't really know if this was fixed in the new version but there are way too many sugar canes in all of my worlds. It actually seems like they are generated everywhere possible.

![screenshot at 2017-09-16 08-33-12](https://user-images.githubusercontent.com/31704619/30509513-f423d0c4-9aba-11e7-81e1-b1112ba7cd1f.png)

**Comment by Wuzzy2** [comment]
Confirmed, this is crazy.

**Comment by Wuzzy2** [comment]
Fixed. This was mostly a problem in the v6 mapgen. Other mapgens were more or less fine.
