### ISSUE TITLE
Sky isn't colored as texture pack's sky

### ISSUE THREAD

**Issue by tacotexmex** [Wuzzy2/MineClone2-Bugs#405]
PixelPerfection comes with its own skybox and while that might not suit MC2 currently, the sky _color_ should at least be changed to that of PP. Depending on the screenshot the brightness differs quite a bit however, so the best is probably to grab the skybox original color directly from texture.

![image](https://user-images.githubusercontent.com/25328789/30596500-8f942e64-9d54-11e7-8bb7-cde83805a52d.png)
RGB color code 0, 110, 160.

![image](https://user-images.githubusercontent.com/25328789/30597169-83c6f092-9d56-11e7-91c7-68f2ba94075d.png)
RGB color code 0, 135, 170.

**Comment by Wuzzy2** [comment]
Sure, why not? But I'm currently more concerned about the sky color at rain or snow. Sofar already complained about that one. I don't know where in the MC resource pack the rain/snow sky color is specified, can someone who knows more about MC resource packs give me a hint, please?

But yeah, I don't want to use the exact skybox either.

**Comment by kingoscargames** [comment]
>  I don't know where in the MC resource pack the rain/snow sky color is specified, can someone who knows more about MC resource packs give me a hint, please?

Texturepacks can have files called "rain.png" or "snow.png"   in 

> assets\minecraft\textures\environment

**Comment by Wuzzy2** [comment]
No, these are the particles. I was referring to the **sky** color.

**Comment by kingoscargames** [comment]
I didnt see:
> sky 

:P

**Comment by tobyplowy** [comment]
@Wuzzy2 You can't change the sky color or add a Skybox texture
this is not possible in default Minecraft you need a mod or mcpatcher or optifine 

So I don't think this should be included in the bace un modded subgame but maybe make it possible to do with texturepacks if it's possible that is ;)

**Comment by tacotexmex** [comment]
Regardless, the **sky color** should match the texture pack's theme.

**Comment by Wuzzy2** [comment]
It is not a goal to adapt to the technical restrictions of Minecraft.

**Comment by Wuzzy2** [comment]
OK, I just tried to just set the sky color as in PP. But it looked horrible, because the fog color changed as well, meaning I had a highly saturated blue color as fog.

**Comment by Wuzzy2** [comment]
I've decided the sky color is just fine. I just leave it as-is.
