### ISSUE TITLE
MineClone 2 Textures Help Needed (Community Input)

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#408]
https://github.com/Gerold55/MineClone-2-Textures/archive/master.zip

**Comment by Gerold55** [comment]
https://github.com/Gerold55/MineClone-2-Textures

**Comment by Wuzzy2** [comment]
So what exactly is the point of this issue?

**Comment by Gerold55** [comment]
To make a more like Minecraft looking texture pack in a sense and to let the community make the textures for MineClone 2

**Comment by Wuzzy2** [comment]
Sorry, this is out of scope for this bug tracker. This bug tracker is only for official bugs and missing features in MineClone 2, not for any unofficial side projects.

Use the forums for stuff like this, please.

**Comment by Gerold55** [comment]
I thought you wanted a texture pack that was the communities for this project I know it shouldn't have technically in the bug tracker but...

**Comment by Wuzzy2** [comment]
The current issues in which I gladly accept contributions are here:

https://github.com/Wuzzy2/MineClone2-Bugs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
