### ISSUE TITLE
"/kill"  doesn't kill if damage is disabled

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#411]

**Comment by Gerold55** [comment]
Commands in general need to be finished

**Comment by Wuzzy2** [comment]
Actually, the `kill` command has no effect if damage is disabled.

**Comment by Doloment** [comment]
In MC:BE "/kill" doesn't kill players in gm1. I think it's right. ._.

**Comment by Wuzzy2** [comment]
I decided to make `kill` intentionally not kill when damage is disabled. Closing.
