### ISSUE TITLE
Ocelots killing players

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#417]
I played on the server and i saw in chat message, a player was killed by untamed cat ocelot, here is the screenshot.
![screenshot_20171004_225947](https://user-images.githubusercontent.com/13905392/31197394-9f89e438-a959-11e7-9b10-dce1ac108cce.png)
This subgame in this server uses a version 0.29.1

Is that a feature that does not exists in Minecraft?
Please, reproduce it.

Ocelots should be killing for chickens, not players.

**Comment by Wuzzy2** [comment]
I think this is fixed now.
