### ISSUE TITLE
Mob footstep sounds (snow) can be heard from far away

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#424]
Very annoying bug, the footstep sounds (esp. snow) of mobs can be heard from far away.

**Comment by WSDguy2014** [comment]
Possibly a duplicate of #346?

**Comment by Wuzzy2** [comment]
I know the problem now.
The sound files are stereo sounds. If the files are converted to mono, it works again.

What a silly bug …

https://github.com/minetest/minetest/issues/6615
