### ISSUE TITLE
Smeltable tools and armor

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#425]

**Comment by Jaen-Minetest** [comment]
I noticed this too. Here is more useful info on smelting tools and armor.

Smelting the following items should yield an Iron Nugget: Iron Sword, Iron Pickaxe, Iron Axe, Iron Shovel, Iron Hoe, Chain Helmet, Chain Chestplate, Chain Leggings, Chain Boots, Iron Helmet, Iron Chestplate, Iron Leggings, Iron Boots, Iron Horse Armor.

Smelting the following items should yield a Gold Nugget: Golden Sword, Golden Pickaxe, Golden Axe, Golden Shovel, Golden Hoe, Golden Helmet, Golden Chestplate, Golden Leggings, Golden Boots, Golden Horse Armor.

I think the recipes for crafting nuggets into ingots are already in MineClone2, but might want to double check that. I'm currently no where near my gaming computer to confirm it.

**Comment by Gerold55** [comment]
Yeah it's already in MineClone 2
