### ISSUE TITLE
Convert stereo sounds to mono?

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#426]
I figured out that stereo sounds are buggy in Minetest.
And there are some stereo sounds in MCL2.
Maybe I should consider converting them all to mono.

Unless https://github.com/minetest/minetest/issues/6615 is fixed.

**Comment by RonnyBarthmann** [comment]
For 3d sound games it is better to use mono sources
from there: yes

**Comment by Wuzzy2** [comment]
Done!
