### ISSUE TITLE
Add trapdoors for each wood

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#434]
MC recently got trapdoors for all woods.

Adding them into MCL2 is a low-hanging fruit, but first I need new textures.

**Comment by kingoscargames** [comment]
The door textures could proably be edited and re-used for this.

**Comment by kingoscargames** [comment]
acacia trapdoor:
![image](https://user-images.githubusercontent.com/29333817/33203371-0c1c2aa2-d100-11e7-84cd-897acce060ef.png)
birch:
![image](https://user-images.githubusercontent.com/29333817/33203379-152cddbc-d100-11e7-838f-77e5baadf732.png)
spruce:
![image](https://user-images.githubusercontent.com/29333817/33203393-1ec8cc14-d100-11e7-99fd-7702ee916203.png)
dark oak:
![image](https://user-images.githubusercontent.com/29333817/33203404-2aaf264a-d100-11e7-97ba-36de261cd0fa.png)
jungle:
![image](https://user-images.githubusercontent.com/29333817/33203410-30a8234e-d100-11e7-9706-53291308c781.png)

**Comment by Wuzzy2** [comment]
Thanks. I've included these with some minor tweaks.

The new trapdoors are now in.
