### ISSUE TITLE
Creepers are too sneaky

### ISSUE THREAD

**Issue by tacotexmex** [Wuzzy2/MineClone2-Bugs#443]
The idea that the player should be terrified of the Creeper is in order. However, it seems that it may spawn 4-6 blocks from player and explode. The player don't stand a fair chance since there's no way of knowing where the mob is going to spawn.

**Comment by kwadroke** [comment]
No sounds from the Creeper warning you that it's there is a problem too.

**Comment by Wuzzy2** [comment]
Creepers also seem to not make the ignite sound sometimes. :-(

**Comment by Wuzzy2** [comment]
The creepers now reliably make a fuse sound. Failing to make the fuse sound was the only real issue here.
But you still need to watch out and act FAST!

**Comment by tacotexmex** [comment]
How far away are they spawned? Found this for reference:
![](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/thumb/4/4a/Mob_spawning_ranges.png/640px-Mob_spawning_ranges.png)
