### ISSUE TITLE
Idea: Mod compatibility layer

### ISSUE THREAD

**Issue by tacotexmex** [Wuzzy2/MineClone2-Bugs#444]
_Though this may be out of scope of the project currently, I’d still like to put forward the idea of having a compatibility mod called default. Sorry in advance if totally out of place, please close if that's the case_

A lot of mods depends of default only for the recipes. These mod could be made to work in MCL2 by simply **aliasing the MTG node names to their MCL2 counterpart**. Of course mods with deeper integration with the MTG API wouldn’t work, but it’d still be both useful and strategic, in so that it has the potential to bootstrap a mod (sub)community targeting MCL2.

**Comment by Wuzzy2** [comment]
MCL2 is *inherently* different from MTG, I don't give a damn about compability with it.

**Comment by yusf** [comment]
I understand but just to be clear the issue was about lazy _mod_ dependencies on MTG, not concession towards MTG itself.

**Comment by tacotexmex** [comment]
I understand that but I just wanted to point out I did not mean _compatibility with MTG_, but simply mods _lazily depending on it only for recipes_. Anyhoo, this is easily done as a 3rd-party mod.
