### ISSUE TITLE
Consider new extendable throwing implementation

### ISSUE THREAD

**Issue by tacotexmex** [Wuzzy2/MineClone2-Bugs#445]
Low priority probably, but if you haven't seen it there's a reimplementation of the current throwing mod, [minetest-mods/throwing](https://github.com/minetest-mods/throwing).

One of the differences between the two is that the new one is an API-only mod (item mod example [here](https://github.com/minetest-mods/throwing_arrows)). Perhaps it will be useful for you to separate the behavior and the items and most certainly for modders such as myself (specifically I want to make [sling](https://github.com/tacotexmex/sling) compatible with MCL2).

**Comment by Wuzzy2** [comment]
Rejected. I like to have my own implementation.

However, I *might* accept patches if they improve the current situation.
