### ISSUE TITLE
Bow and arrows: No fluid charging

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#45]
> 2. Bow almost useless, it requires on arrows on hotbar attached like this:
> ![screenshot_20170219_114109](https://cloud.githubusercontent.com/assets/13905392/23101279/82fd28d0-f698-11e6-9466-3473763b2d95.png)
> !Not good, bad durability: 9 shots (sometimes).
> Unreloaded bow: No shooting.
> Reloaded bow on low charge: shooting on low speed.
> Reloaded bow on medium charge: shooting on medium speed.
> Reloaded bow on maximum charge: shooting on maximum speed + 50% chance for critical hit.
> There is no way to cancel charging bow if it's not selected or storing on chest.

Yes, the bow needs a lot of love. All of this is confirmed.

Proper bow charging requires a change in Minetest: https://github.com/minetest/minetest/issues/5212

@WSDGuy2014

**Comment by Wuzzy2** [comment]
@WSDGuy2014.

The bows have been improved. They now kinda resemble Minecraft gameplay, but there's no real fluid bow charging.
Basically you can charge the bow once by rightclicking and shoot with leftclick. So the basics work.

Arrows can now be placed anywhere in inventory.
Bows have infinite shots in creative mode.
Durability bugs have been fixed.
Critical hit has been implemented.
Damage and range increases with charge.

I don't close this because the most important feature, FLUID bow charging by holding down the right mouse button, still doesn't work and won't work for a while because of missing engine support.

**Comment by Wuzzy2** [comment]
Candidate mod:

https://github.com/Arcelmi/minetest-bows

**Comment by leorockway** [comment]
The charging seems interesting. Although not completely fluid it does a good job at pretending it is (which is good until MT has an engine change for that sort of thing). The rest of the mod has some issues. For instance, if you shoot all the way up against the sky, it never falls. It just keeps going up and up.

**Comment by Wuzzy2** [comment]
I have incorporated code from Arcelmi's mod to implement fluid bow charging!
Bows now charge fluidly.

Any potential issues with the mods have been resolved. I have not experienced that ever-rising arrow bug.
