### ISSUE TITLE
Explain command blocks properly

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#450]
I was trying to use the command block and I can't seem to get a code to work please make a how-to page on it.

**Comment by Wuzzy2** [comment]
There is an in-game help for command blocks, but from your responses so far I concluded it's too confusing.
I accept this issue now.

I should rewrite the help probably.

The current official help for command blocks are:

* The entry for the command block itself (Help > Blocks > Command Block)
* The entry for server commands (Help > Advanced topics > Server commands)

The help mod probably needs improvements as well. I probably need to add something like “see also” buttons.

**Comment by Gerold55** [comment]
Maybe eventually add pics 😂😂😂

**Comment by Wuzzy2** [comment]
I rewrote the help page and added examples. I hope it should now be easier to understand. Note the command block worked all the time, it was just not clear how to use.

---

Basically you just enter the commands like you do in the console, but without the slash. `@nearest` etc. are *optional* placeholders for player names.

Valid examples:

``` weather snow```

```give Player1 mcl_core:stone 64```

```give @nearest mcl_core:apple```
