### ISSUE TITLE
Baby animal growing into adults should match textures

### ISSUE THREAD

**Issue by rasusmilch** [Wuzzy2/MineClone2-Bugs#459]
In testing my mob pen in a farm I added some ocelots. I bred two of them which gave me a baby orange tabby. This baby grew up into a grey Siamese cat?! Not a big deal, but very strange!

**Comment by Wuzzy2** [comment]
Recessive genes. ;-) https://en.wikipedia.org/wiki/Recessive

Just kidding. Yeah, this behaviour is of course not intended.

**Comment by Wuzzy2** [comment]
Fixed in e246b5d0bba3489051351c692aee2b575a7d0311.

The child of two cats now simply has the fur of one of the parents chosen randomly.
