### ISSUE TITLE
mod naming error with 0.36 update

### ISSUE THREAD

**Issue by dawgdoc** [Wuzzy2/MineClone2-Bugs#465]
After pulling your latest changes, as of 2018-02-07 20:23:04, I received this error:

`2018-02-10 01:23:57: ERROR[Main]: ModError: Error loading mod "PLAYER": Mod name does not follow naming conventions: Only characters [a-z0-9_] are allowed.
2018-02-10 01:23:57: ERROR[Main]: Check debug.txt for details.`

when entering an existing world. I then deleted the old debug.txt, created a new world and received the same error. Looking at the mod directories I see all of the mod names are completely capital letters. As in : CORE, MAPGEN, PLAYER.  Is this the cause of the error?

**Comment by Wuzzy2** [comment]
Which MT version do you use?

**Comment by dawgdoc** [comment]
Sorry, for not providing enough information.

I am using MT 0.4.16 from the [Ubuntu Stable PPA](url=https://launchpad.net/~minetestdevs/+archive/ubuntu/stable) on LinuxMint 18.3, based on Ubuntu 16.04(Xenial). This is on a laptop with 12Gb ram, AMD A12 processor.

**Comment by Wuzzy2** [comment]
WTF?
This must work under MT 0.4.16. Sadly, I can't reprodce this.
Are the aforementioned folders empty? If not, what was inside? Did you find a `modpack.txt`?

In case these folders were empty, your installation probably went wrong. In this case, delete MCL2, download again and try again.

**Comment by dawgdoc** [comment]
The folders are definitely not empty, but I did not find a modpack.txt. 
![mcl2-modsfolders](https://user-images.githubusercontent.com/26846591/36335903-1138bc9a-1349-11e8-84ef-fd03b349cfcc.png)
