### ISSUE TITLE
Sugar cane does not update when it is replaced by piston head

### ISSUE THREAD

**Issue by Doloment** [Wuzzy2/MineClone2-Bugs#467]
![screenshot_20180217_140742](https://user-images.githubusercontent.com/22934348/36339007-3ad18104-13ee-11e8-97ef-96869a0150f9.png)
![screenshot_20180217_140815](https://user-images.githubusercontent.com/22934348/36339008-3e5bbae2-13ee-11e8-979b-12268a7d27ad.png)
![screenshot_20180217_140819](https://user-images.githubusercontent.com/22934348/36339014-6039de14-13ee-11e8-8d46-209a72ef9ead.png)
![screenshot_20180217_140834](https://user-images.githubusercontent.com/22934348/36339009-43885034-13ee-11e8-9d51-7299b24a9843.png)
![screenshot_20180217_140836](https://user-images.githubusercontent.com/22934348/36339011-471a4df6-13ee-11e8-9ca5-c761fc4fa730.png)

**Comment by Bu-Gee** [comment]
I am working near this code.  I'll see if I end up working on this as well.

**Comment by Bu-Gee** [comment]
Actually, I modified some code that might already do this.  I will test to see if it does.

**Comment by Bu-Gee** [comment]
This does indeed appear to be fixed in the patch included in #469

**Comment by Wuzzy2** [comment]
Fixed by Bu-Gee in d2f01c68f520913b487096fc2549fe2648a32a33.
