### ISSUE TITLE
Arrow projectile entity can be killed.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#474]
![image](https://user-images.githubusercontent.com/13905392/40558293-8323cb88-605b-11e8-8a64-1b67556c645a.png)

**Comment by WSDguy2014** [comment]
I was played on this multiplayer server and i'm not sure what is the current MineClone 2 game version is using? maybe the latest version 0.38.0. Bow and arrows are reworked in version 0.37.0 and you forgot to make the arrow projectile invulnerable?

**Comment by Wuzzy2** [comment]
Ahaha! Oops, yes, now I get it. Fixed, thanks.
