### ISSUE TITLE
Furnace issues in subgame version 0.10.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#50]
Progress bar smaller and does not show/work if its cooking something.
![image](https://cloud.githubusercontent.com/assets/13905392/23129378/19a734f4-f78b-11e6-96cb-79c3acff4223.png)

Furnace output slot is full and its trying to cook something, but does not fit here and wasting a fuel items.

Automating storing items slot with hoppers on furnace also an issue, bottom for output slot its fine, on top for input slot also fine too, but 4 sides are supposed to be for fuel slot, not input slot.
![image](https://cloud.githubusercontent.com/assets/13905392/23129656/2b04fdca-f78c-11e6-82b4-7b48fc878400.png)

**Comment by Wuzzy2** [comment]
YES!
The furnace is very important, so this issue must be fixed ASAP.

**Comment by Wuzzy2** [comment]
Fixed since 6d9eeb24ec7764f2506dab16d24f7b382e5c5fb3 or earlier.
