### ISSUE TITLE
Shulker boxes issues in subgame version 0.10.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#52]
Shulker boxes must be faceable facedir like a wood.

If shulker boxes contains any items on storage, putting on dispenser slot and activating to place: shulker boxes contains empty, same thing on dropper.

Another issue, trying to store items on shulker boxes using with hopper on top, it crashes, same thing on 4 sides, it crashes the game. Getting items off in shulker boxes on bottom is fine. Works on droppers.

**Comment by Wuzzy2** [comment]
Thanks for going crazy on bug reporting, this is important work! :-)

About facedir: Do you mean, shulker boxes should rotate in all 6 directions?

As far I know, dispensers are not supposed to place items into containers, only droppers are.

I was able to reproduce the hopper crash, but only at a side. But it's still a crash. Oops!

**Comment by WSDguy2014** [comment]
> About facedir: Do you mean, shulker boxes should rotate in all 6 directions?

Yes.

**Comment by Wuzzy2** [comment]
Thanks.

Hopper+shulker box crash is now fixed in 40783d2ca64012696481df64739238ff0c526cfe.

**Comment by Wuzzy2** [comment]
- Shulker box inventory is no longer destroyed when placed by dispenser
- Shulker box inventory is no longer destroyed when placed by dropper (actually, the dropper destroyed the item metadata of all items, so this also affected tool wear, written books, etc.)
- Shulker boxes now rotate depending on how you place them.

Everything is fixed! Closing.
