### ISSUE TITLE
Storing shulker boxes with dropper glitch in subgame version 0.10.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#57]
Dropper is trying to put hopper item at shulker box, it crashes.

https://www.youtube.com/watch?v=8UfA3T_-XqA

I'm going to be called the subgame with only 1 splash text:
![screenshot_20170219_203310](https://cloud.githubusercontent.com/assets/13905392/23132851/a5e2f9c4-f797-11e6-8dfb-e9b73a7752c1.png)

**Comment by Wuzzy2** [comment]
I guess it is fixed in development version. I keep this issue open. I'm going to release today, so you can test it again with 0.11.0.

**Comment by WSDguy2014** [comment]
I tested in 0.11.0, seems to be fixed...
