### ISSUE TITLE
Lighting continues to strobe

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#61]
After a bright lightning flash, sky continues to strobe off and on around twice a second. 

Running Minetest 0.4.15 and MC2 commit 94a2c0fe0d721f9260f12f4da909c7c8b2405bd9 on Debian Linux 8 x86_64

Game settings:
Smooth Lighting - On
Particles - On
3d Clouds - On

Node Outlining
Fancy Leaves

Texturing:
No Filter
No Mipmap

Antialiasing:
None

Shaders - On

**Comment by kwadroke** [comment]
Not sure if it is related but I see an occasional grey flash in the sky when the weather is clear. Seem like it started when weather was added. Could be related.

**Comment by Wuzzy2** [comment]
I guess it should be fixed now. Can you please test?
I agree, it was very annoying, I probably do another release today just because of that. ;-)

**Comment by kwadroke** [comment]
Will try to check it out tonight.

**Comment by Wuzzy2** [comment]
Okay, I haven't seen this bug for quite a while now, so it is very probably fixed. :-)

**Comment by kwadroke** [comment]
Haven't seen it myself yet.

**Comment by kwadroke** [comment]
Confirming - has been fixed.
