### ISSUE TITLE
Skies should be grey when snowing

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#63]
Currently (commit 94a2c0fe0d721f9260f12f4da909c7c8b2405bd9) when snow is falling the sky is sunny (during the day of course). To be more realistic, when it is snowing, the skies should be grey like it is when it is raining.

**Comment by Wuzzy2** [comment]
Fixed yesterday.

**Comment by kwadroke** [comment]
Confirmed fixed.
