### ISSUE TITLE
Redstone bugs, glitches and problems in subgame version 0.11.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#65]
These redstone glitches/problems includes: Infinite powered redstone strength, pistons texture problems, pistons don't push players or/and entities (due old version of Mesecons mod), (note: includes water, lava and lava cooling does not make sounds), rejoin the world and repeater clock stopped, bad redstone update block, floating redstone wire (it's not supposed to be floating), repeater icon texture must be an item, not block, incorrect repeater placing, no comparators (it's going to be hard coding for you?), no observers, no tripwire hook, no tripwire itself (used as string to place it), redstone torch are called "Mesecon Torch"? and others.

https://www.youtube.com/watch?v=tgTwvFflXB4

**Comment by tobyplowy** [comment]
@Wuzzy2 I think the best way to test Redstone is to replicate some redstone machines (tutorials)

Try to replicate some of this stuff XD

https://m.youtube.com/playlist?list=PLFm1tTY1NA4elJWJDpzQ6ANA0u2gtCs0t

https://m.youtube.com/playlist?list=PLFm1tTY1NA4cECrn-hM-_oO7f2MtFs645

https://m.youtube.com/playlist?list=PLFm1tTY1NA4cFes8tk7XgrxaMTuApEUxz

**Comment by Wuzzy2** [comment]
Redstone is serious business. The fact alone that real redstone wires have limited range, instead of infinite already shows that this is going to take a lot of work.
It also means that I will likely lose all compability with Mesecons, which sucks.

**Comment by Wuzzy2** [comment]
The bug report as a TODO list:

* [ ] Infinite powered redstone strength
* [ ] pistons texture problems
* [ ] pistons don't push players or/and entities (due old version of Mesecons mod)
* [ ] rejoin the world and repeater clock stopped
* [ ] bad redstone update block
* [X] floating redstone wire (it's not supposed to be floating)
* [X] repeater icon texture must be an item, not block
* [X] incorrect repeater placing
* [ ] no comparators (it's going to be hard coding for you?)
* [ ] no observers
* [ ] no tripwire hook, no tripwire itself (used as string to place it)
* [ ] redstone torch are called "Mesecon Torch"?

**Comment by Wuzzy2** [comment]
Status update:
Redstone wires don't float since a while anymore.
I have done some redstone repeater rework and it should now look and behave like the real redstone repeater.

> no comparators (it's going to be hard coding for you?)

Hmm, not sure. The hard part would actually be to implement *finite* signal strength, instead. But nothing impossible. The comparator itself may not be the difficult part. It took me one day to implement the dropper and 2 days to implement the dispenser. I suspect it would take me about the same time to implement the comparator.
Adding components to the mesecons is generally incredibly easy, but to be Minecraft-like, vanilla Mesecons is not enough, especially because of the signal level.

**Comment by Wuzzy2** [comment]
>  pistons texture problems

I am not sure what you're talking about. Please explain. Do you maybe mean that in old versions the piston arm was too thin? I fixed that, the textures look OK now.

**Comment by Wuzzy2** [comment]
Floating activated redstone wires are now fixed, too.

**Comment by Wuzzy2** [comment]
Closed in favor of https://github.com/Wuzzy2/MineClone2-Bugs/issues/353.
