### ISSUE TITLE
Players and armor stands unable to wear pumpkin on helmet slot in subgame version 0.11.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#66]
Pumpkins is used to prevent enderman get angry.

**Comment by kingoscargames** [comment]
i am gonna work on this tomorrow (currently 22:16 for me)

**Comment by Wuzzy2** [comment]
OK, thanks. Patches are very welcome, because they are easy to merge.
Please note I am planning to replace the armor stand entirely one day, because it must be an entity.

For more complex changes, using Git is also an option. In this case, fork the MineClone 2 repository (http://repo.or.cz/MineClone/MineClone2.git), then commit your changes in a new branch and publish your forked repository somewhere where I can see it.

**Comment by kingoscargames** [comment]
textures needed:
![mcl_farming_pumpkin_face](https://user-images.githubusercontent.com/29333817/27010709-0ac610dc-4eab-11e7-9b62-bfdbbcad98d2.png)
![mcl_farming_pumpkin_face_preview](https://user-images.githubusercontent.com/29333817/27010708-0ac16e56-4eab-11e7-9060-a58eef1bad7a.png)

edited line of code:
groups = {armor_head=0.0000000000000001, handy=1,axey=1, plant=1,building_block=1, dig_by_piston=1},

screenshot:
![screenshot_20170611_132834](https://user-images.githubusercontent.com/29333817/27010713-2bb41b86-4eab-11e7-93d3-c4d064da354b.png)

bug:
![screenshot_20170611_131923](https://user-images.githubusercontent.com/29333817/27010714-34629bc2-4eab-11e7-8698-94495d1099e7.png)

**Comment by kingoscargames** [comment]
the hardest part was to find the register code of the block

**Comment by Wuzzy2** [comment]
I added wearable pumpkins, also work on armor stands. Actually, writing just `armor_head=1` would be correct here, group ratings only take integers. The actual armor strengh is in `armor_heal`, not in `armor_head`, if I recall correctly.

Still TODO:
* Doesn't make endermen angry
* Reduced mob detection range
* Obstructed view while wearing

So currently, pumpkin helmets are just for fun.

**Comment by kingoscargames** [comment]
no armor_heal is something different than armor_head

**Comment by Wuzzy2** [comment]
Pumpkins and heads can be worn now, also on the armor stand. I'm closing this, but I will open new issues for the remaining missing features of heads/pumpkins.
