### ISSUE TITLE
Weird glitch to obtain spawn egg in subgame version 0.11.0?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#71]
For example, if you tame a chicken with 8 seeds, then right-click tamed chicken with empty hand to get a chicken spawn egg sometimes.

Same thing problem with horses, if any horses with saddle on (which its tamed) left-click to punch a horse, to get unknown item, it supposed to be a spawn egg.

**Comment by Wuzzy2** [comment]
Partially fixed. Chickens, pigs and cows can not be collected as spawn eggs anymore.
Horses are unbelievably broken and need a major rework.

**Comment by Wuzzy2** [comment]
Okay, you can't punch horses to get their spawn eggs anymore, so at least this issue is fixed. I open a new issue just for horses.
