### ISSUE TITLE
Tamed wolves are useless in subgame version 0.11.0!

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#74]
I tamed wolf just requires only 1 bone, not 2 or more, then i hit a sheep 1 time for testing example to be killed by our tamed wolf (wolves), but it does not work! Sometimes tamed wolf (wolves) still trying to kill me (just like old Minecraft version of beta "Beta 1.6 - Prior to this update, players hurting themselves with arrows would cause all of their tamed wolves to attack the player." from Minecraft Wiki). http://minecraft.gamepedia.com/Wolf#History

**Comment by kwadroke** [comment]
I've also experienced wolves attacking player if attacking a close neutral mob (cows, sheep, pigs ,etc).  Also can tame wolf with one bone. Tamed Wolves will also despawn if too far away after time.

Still doing this as of d3b3c596bd3f029ed690959384f474baab31a8c6

**Comment by Wuzzy2** [comment]
Wolves have been removed because they were pointless and buggy. Better to re-do them from scratch.
