### ISSUE TITLE
Free/libre 16×16 textures

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#76]
MineClone 2 should switch to 16×16 textures, but I don't know a good AND free AND Minecraft-like resource pack.

Minimum requirements:
* Libre license (compatible with LGPLv2)
* 16×16
* Not a total conversion (e.g. weird sci-fi stuff like turning a oak tree trunk into steel blocks or something like that)

**Comment by tobyplowy** [comment]
@Wuzzy2 there is plans to make a Summerfields 16x16 wuld that be useful? (Bdw I help making updates for Summerfields so it's not hard to make this happen)

**Comment by Doloment** [comment]
Original
![bf61e3ef4d91ffe323b0065f5c31dd4a](https://cloud.githubusercontent.com/assets/22934348/26570571/7d2d24c2-453b-11e7-8bbe-67f57d773260.jpg)
My version
![f69 default_tool_diamondpick inettools net resize image](https://cloud.githubusercontent.com/assets/22934348/26570713/36bc96a2-453c-11e7-9b10-3b2d577ce7d2.png)

**Comment by Wuzzy2** [comment]
Thanks, but for a texture switch, I gonna need a full or near-full texture pack. Otherwise the unholy alliance of 16×16 and 32×32 textures will look really bad. :D 

The authors of Summerfields don't seem to give me permission, nor change the license. I probably would not have picked Summerfields anyway.

**Comment by Doloment** [comment]
It's one texture. I can make all texturepack.

**Comment by Wuzzy2** [comment]
If you want to make *all* the textures, that would be great!
But be aware that this is an ambitious project, there is a ton of textures to make. Are you sure you have the stamina to finish this till the end?

Did you also search for free/libre non-weird 16×16 textures beforehand? Please list anything you have found. I would very much prefer to just use a texture pack which is already readily available. I can't believe we really have not a single texture pack which fits these very simple criteria.

I would really like to avoid to go the path of starting all over with the textures. I honestly only like to do this as a last resort.

But if you really want to do this:
Keep in mind that this is for default textures, not just any texture pack. So I can't take anything weird or obscure.
And obviously absolutely no copies from original Minecraft textures, or anything else bound by copyright.
Apart from that, I do not want to take away too much from your artistic control.

Beware, I can not guarantee yet that every texture currently in the game will stay that way. But 98% of node and item textures should be safe. When in doubt, just follow the format of the original Minecraft texture. Just pretend you'd be making a Minecraft texture pack. :-)

An exception (for now) are those gray grass/leaves textures, those need to be colored for MCL2. But maybe you want to keep the original gray version anyway, I might still need it later.

There are a few textures in the game which do dilberately not follow Minecraft format, mostly for technical reasons. One example is the texture for mature cocoa. Don't ask me why. xD
Mob textures are probably completely out of sync, don't bother with those for now; or just use the Minecraft templates.

I actually wanted to write down all these texture oddities which I definitely try to keep on an absolute minimum. I also wanted to write a CSV file with exact mapping from Minecraft file name to MCL2 file name, plus those files which differ from the original. That way, it should be easy as cake to change the default textures in MCL2.

I also plant to eventually clean up the few inconsistent textures, in the best case scenario this would make it possible to copy every file verbatim from any given MC texture pack with only the file names needing to be changed, so it can be fully automated.



So …
What do you suggest we should do?

**Comment by Doloment** [comment]
Just wait

**Comment by Wuzzy2** [comment]
@Doloment: Would you like to contribute 16×16 textures for the mobs_mc mod?

https://github.com/maikerumine/mobs_mc

If you want to, please post an issue in https://github.com/maikerumine/mobs_mc. Maybe even with a sample for a single mob. But not more (for now) since this needs to be discussed with maikerumine as well.

`mobs_mc` stays true to the Minecraft texture format, so if you made MC texture packs before, it should be easy for you.

**Comment by Wuzzy2** [comment]
Possible candidate:

* Pixel Perfection: https://minecraft.curseforge.com/projects/pixel-perfection-freshly-updated

Although it is a bit too overstyled for my taste, but this may be acceptable. I should definitely write a conversion script or something.

**Comment by Wuzzy2** [comment]
Now high priority because I learned Faithful Vanilla is non-free because it is a derivate work of Faithful. >_>

**Comment by leorockway** [comment]
This might help a bit. The MT specific textures were ported over: https://forum.minetest.net/viewtopic.php?f=4&t=14289&p=252700&hilit=pixel+perfection#p252700

**Comment by Wuzzy2** [comment]
Nope, this doesn't help at all because MCL2 has an entirely different directory structure and different file names.

**Comment by leorockway** [comment]
But there's a script to convert MC textures too MT in that thread. Wouldn't it be easier to modify that one too work with MCL2?

**Comment by Wuzzy2** [comment]
This script is only to create texture packs, not to change the original textures stored in the mod folders.

For your interest: I think the texture file names should by now have stabilized. While I don't want to exclude the possibility of minor future changes right now, creating a texture pack at this stage should be relatively safe at this point.

**Comment by tobyplowy** [comment]
@Wuzzy2 I can make a Minecraft like texture pack (can't promise anything)
But there's one thing you will have to keep in mind I'm the owner of the textures if you're ok with that than I can try to get something done if I have time

**Comment by Wuzzy2** [comment]
I will only consider texture packs if they match the above 3 requirements.

To clarify: “Libre license” means a license which meets all of the following criteria:
- Allows copying and redistribution
- Allows usage of **any** kind
- Allows remixing
- Allows copying and redistribution of those remixes

Examples: WTFPL, CC BY 4.0, CC BY-SA 4.0, CC0 1.0
Counter-examples: CC BY-SA-**ND**, CC BY-**NC**, no license (“All rights reserved”)

Any texture authors will be credited, regardless of license.

A sample of 10 textures (preferably for `mods/ITEMS/mcl_core`) would be nice.
Currently, I still tend to continue to use Pixel Perfection, unless something better comes along (better = less weird mob textures and more faithful to the original while still being different enough).

**Comment by Wuzzy2** [comment]
Some PP alternative textures by MysticTempest:
https://forum.minetest.net/viewtopic.php?f=50&t=16407&start=475#p283736

**Comment by Wuzzy2** [comment]
Pixel Perfection is now in!
The lion's share has been done, but a few textures still need conversion.

TODO:
- [ ] Double Chest
- [ ] Ender Chest
- [ ] Lookup Tool
- [ ] Armor preview
- [ ] Armor textures
- [ ] Redstone trails
- [ ] Melon Stem
- [ ] Pumpkin Stem
- [ ] Armor inventory slots
- [ ] Glazed Terracotta (optional, because of MC 1.12)

**Comment by Wuzzy2** [comment]
:tada: :balloon::tada: :balloon::tada: :balloon:
Almost all textures have been successfully converted to Pixel Perfection!

Glazed terracotta will be tracked in #336. Closing.
