### ISSUE TITLE
Armor outline needs to be texture change for armor slot.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#77]
![image](https://cloud.githubusercontent.com/assets/13905392/23176469/c5ec589e-f86b-11e6-9e9a-06d2e11734de.png) -->![image](https://cloud.githubusercontent.com/assets/13905392/23176601/6c4f49f8-f86c-11e6-9c90-51d2cdaf8f65.png)

Must be an 32x32 Minecraft texture for this.

**Comment by Wuzzy2** [comment]
Fixed since ea9e80e020a6f640950f4827c186157edc18a52e.
