### ISSUE TITLE
Sneak-jumping makes player jump higher

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#78]
If you jump while sneaking, you jump slightly higher, but this should not be possible.

0.10.0

Probably needs an engine change as this behaviours seems to be hardcoded in Minetest.

**Comment by WSDguy2014** [comment]
If you stand on slime block and do hold sneak and jump, will make higher.

**Comment by WSDguy2014** [comment]
Current subgame version is "0.11.0" not "0.10.0".

**Comment by Wuzzy2** [comment]
Fixed in Minetest 0.4.16.
