### ISSUE TITLE
Horses are broken

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#80]
Horses? Forget them! They are unbelievably broken, don't even try to ride on them. They are more like wheat-fueled cars than actual animals.
I don't even know where to start, there's so much wrong about horses.

Probably best to burn the entire horse code and start over.

**Comment by tobyplowy** [comment]
> wheat-fueled cars than actual animals.

What are you talking about does [This](http://www.freakingnews.com/pictures/70000/Bently-Car-Horse-70369.jpg) look like a car to you XD

**Comment by Wuzzy2** [comment]
Horses have been removed. For now.
