### ISSUE TITLE
Sprinting causes to crash.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#81]
Enabled only creative mode, disabled damage.
Try to reproduce in subgame version 0.12.1
![image](https://cloud.githubusercontent.com/assets/13905392/23204301/b1873dbe-f8ee-11e6-8c5b-913e9ab818ff.png)

**Comment by Wuzzy2** [comment]
Fixed in c60cff8f812464c9567a35063167124d5ec73587.
