### ISSUE TITLE
Void air blocks are pushable and pullable with pistons and destroyable with falling sand blocks.

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#85]
In subgame version 0.12.1

There's no way to trying quickly clear sand blocks using with torch or redstone torch.
https://www.youtube.com/watch?v=96eHTKQhww0&t=2h22m8s

**Comment by tobyplowy** [comment]
@Wuzzy2 NOTE he is using mods or a texturepack in this video (but the sand torch thing is in the normal game the sand layeres and mini map are not)

**Comment by Wuzzy2** [comment]
Please only 1 issue per bug / missing feature.
Void is now a piston stopper, so pistons should not affect the void and the void should prevent pistons from pushing into.

The falling block bug is now tracked here: https://github.com/Wuzzy2/MineClone2-Bugs/issues/85

Closing …

**Comment by WSDguy2014** [comment]
@tobyplowy It's a modpack for Minecraft, ignore it. MineClone 2 Must be Vanilla Minecraft-Like.
