### ISSUE TITLE
Slabs on sideways in subgame version 0.12.1

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#91]
![image](https://cloud.githubusercontent.com/assets/13905392/23263455/fa286b30-f9e6-11e6-9c02-5d24f13415b1.png)
Tested on any slabs.

**Comment by Wuzzy2** [comment]
Slabs have been completely reworked. This issue is now fixed (since b9a40f2b7f14f5de0e5b89dab9810e8d166a17a9)
