### ISSUE TITLE
Selecting barrier block should be create a barrier particles

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#93]
Without selecting barrier on hotbar, does not appear particles.
![image](https://cloud.githubusercontent.com/assets/13905392/23264344/ae99acd0-f9e9-11e6-93aa-733a18ab0a20.png)

Selecting barrier on hotbar, should be appear particles.
![image](https://cloud.githubusercontent.com/assets/13905392/23264416/e7e15f10-f9e9-11e6-9f9f-5ca41d69299e.png)
http://minecraft.gamepedia.com/Barrier

**Comment by Wuzzy2** [comment]
Ohhhhh! Those things are implemented as particles. That's interesting. With this knowledge, implementing this was easy. :-)

Implemented since bb9d6cf03726039764bb7af919720be9a6c07616.
