### ISSUE TITLE
Falling nodes fall infinitely on fence/wall; can obtain piston arm with trick

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#98]
I found way to get unobtainable items with out using /giveme or give command in survival mode. For example piston arm or sticky piston arm, that drops itself.
Here is the construction that i build. I'm will be called "Block Breaker":
![image](https://cloud.githubusercontent.com/assets/13905392/23332117/b2d554e0-fb7c-11e6-9b25-f00f51a89f9c.png)
On top one is for any piston type, normal or sticky.
Note: Any falling sand blocks are supposed to trying land on any fence posts, any closed fence gates or any wall. Just like same as Minecraft, if Mojang finally fixed these infinitely falling sand glitch in future update, you will start to try fix these infinitely falling sand glitch. https://www.youtube.com/watch?v=x4NxcSDSvps&t=12s
Activate 2 pistons at the same time, falling sand block should land on bottom piston arm and also destroys top piston arm and it looks like this:
![image](https://cloud.githubusercontent.com/assets/13905392/23332206/6d4b1d72-fb7e-11e6-99e9-3bf24cc7c92c.png)
Any piston arm facdir are drops itself. You can do like this, to get any piston arm drop itself, for making a table:
![image](https://cloud.githubusercontent.com/assets/13905392/23332223/c3d8f754-fb7e-11e6-9209-f1969ba395b2.png)
Or facing on bottom:
![image](https://cloud.githubusercontent.com/assets/13905392/23332315/496ff9e8-fb80-11e6-8c24-edd9b0dbd886.png)

If you place any piston arm blocks, you cannot break, if you try to break any piston arm block in survival mode, it will not work, can only be break using TNT or creeper explosion.

**Comment by Wuzzy2** [comment]
Confirmed. The main problem here is that the gravel never stops falling on a fence. This is probably related to the odd collision box of fences, which goes 0.5 node lenghts above the usual cube.

I probably should talk to the Minetest developers about this one.

**Comment by kingoscargames** [comment]
But this is also in mc

**Comment by Wuzzy2** [comment]
The goal of MCL2 is not to replicate bugs. This is an obvious bug and has many unintended effects. This bug definitely must be fixed IMO.

**Comment by kingoscargames** [comment]
:(

**Comment by kingoscargames** [comment]
https://www.youtube.com/watch?v=N552BBiX8Ys

**Comment by kingoscargames** [comment]
the piston thing should but i was talking about the sand

**Comment by Wuzzy2** [comment]
Falling nodes no longer fall infinitely on fence posts.
